### ISSUE TITLE
Remove automatic checkout for reviewers

### ISSUE THREAD

**Issue by Knorrke** [serlo/serlo.org#100]
The automatic checkout is a workaround introduced, because in early times you weren't able to work if no one had reviewed your last change. The workflow is a lot different now and we can make the automatic checkout optional.

**Comment by inyono** [comment]
- [ ] Add option to opt-out of reviewing if you have reviewing rights (by default, all revisions should be reviewed)
- [ ] Maybe track that in the checkout event
