### ISSUE TITLE
Improve Diff-View

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/serlo.org#103]
- [ ] Handle long lines,
- [ ] reduce structure overhead ("plugin:", "state")
- [ ] remove lines (maybe then also a clearer separation, when unchanged stuff is hidden)
- [ ] highlight changes in render
- [ ] jump to changes from code
- [ ] beautify html code in text mode
- [ ] vorschau + aktuell nebeneinander
- [ ] html diff in vorschau + aktuell -> berechnung der diff aus dem html
- [ ] diff berechnung mit verschiebungen
- [ ] https://de.serlo.org/entity/repository/compare/148693/154316

**Comment by yolo-bird** [comment]
Possibility to check anchors in the preview: 
In der folgenden Bearbeitung hat Ole Anker gesetzt und damit auf Zwischenüberschriften verlinkt. In der Reviewing-Ansicht hat das überhaupt nicht funktioniert. Aktuell gibt es keine Möglichkeit einen Anker zu testen ohne den Inhalt freizugeben:
https://de.serlo.org/entity/repository/compare/140479/150399

**Comment by inyono** [comment]
Well, that's because they aren't linked correctly...
- Linking to other entities: `/<id>`, e.g. `/123123123`
- Linking to an anchor: `#<anchor>`, e.g. `#entity-unrevised-finden
- Linking to external stuff: `https://<url>`, e.g. `https://de.serlo.org`
Actually, if it doesn't work in the preview in the diff view, its most likely not linked correctly.

**Comment by yolo-bird** [comment]
Thanks. I'll keep that in mind.

I have a further issue. In this edit: https://de.serlo.org/entity/repository/compare/140479/150448
links have been altered. In the diff-view  "keine Änderungen" appears.

**Comment by inyono** [comment]
Which link(s) have been changed supposedly?

**Comment by yolo-bird** [comment]
In this edit Renate corrected the first Link "chemische Zeichensprache" (does not work in the old version, but in the preview of the new version). Yet the Diff-View shows no changes.
https://de.serlo.org/entity/repository/compare/32712/150834

**Comment by inyono** [comment]
Thanks @yolo-bird, I can work with that. I created an issue for that specific bug, see https://github.com/serlo/serlo.org/issues/308.

**Comment by yolo-bird** [comment]
Moved to https://docs.google.com/document/d/1rSkFo2JtsSwHHsbosQcgAN4EzeePXLnqi_eCFpUM3u4/edit#heading=h.vy4mt8ku925l
