### ISSUE TITLE
Deployment of redesign to staging

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/serlo.org#111]
Infrastructure is running on local system, now we can test it on staging servers to check everything works fine

**Comment by Entkenntnis** [comment]
I'm taking a look at the dependencies of the next-server ...

**Comment by Entkenntnis** [comment]
Ok, the new serverless.js server (sic) has no npm dependencies and is only relying on the `./public` and `./next` folder (after build). For now it is serving the static files by itself. Set environment ASSET_PREFIX and NEXT_ASSET_PREFIX to the corresponding host.

**Comment by inyono** [comment]
Done :)
