### ISSUE TITLE
static-assets fails to start

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/serlo.org#122]
Error: nginx: invalid option 'nginx'

workaround: add this to docker-compse.yml:

```
 static-assets:
    entrypoint:
      - nginx
      - -g
      - 'daemon off;'
```

**Comment by inyono** [comment]
Can't reproduce on my machine. Let's check that next time at yours

**Comment by Entkenntnis** [comment]
also can't reproduce

**Comment by inyono** [comment]
😄
