### ISSUE TITLE
fonts load from de.serlo.localhost:4567 in dev

### ISSUE THREAD

**Issue by inyono** [serlo/serlo.org#123]
Does only occur in dev (since ASSET_PREFIX == NEXT_ASSET_PREFIX in production): the font isn't loaded correctly, since it is requested via NEXT_ASSET_PREFIX instead of ASSET_PREFIX

**Comment by Entkenntnis** [comment]
fonts get loaded multiple times, two times correctly and two times unprefix - no idea why this is happening

**Comment by Entkenntnis** [comment]
found out the reason, we need to pass assetPrefix to the client
