### ISSUE TITLE
Don't resolve static assets in production

### ISSUE THREAD

**Issue by inyono** [serlo/serlo.org#124]
Currently, `serverless.js` does resolve static assets when the request isn't handled by a page. While this is currently needed in dev (to serve .next/static), we shouldn't do this in production. For example, you could define a special serverless.js for dev (that basically extends the serverless.js for prod) and add a different entry point here: https://github.com/serlo/serlo.org/blob/master/packages/public/frontend/Dockerfile#L8. Feel free to suggest better solutions

**Comment by Entkenntnis** [comment]
added env-var `SERVE_ASSETS` which is only set to true in development

**Comment by inyono** [comment]
see https://github.com/serlo/serlo.org/issues/126#issuecomment-561103069
