### ISSUE TITLE
Implement health check

### ISSUE THREAD

**Issue by inyono** [serlo/serlo.org#126]
Kubernetes requires services to implement health checks to enable all its functions. Please implement a health check for the frontend service similar to https://github.com/serlo/serlo.org/blob/master/packages/public/editor-renderer/src/index.ts#L45

**Comment by Entkenntnis** [comment]
`/` => `frontend@0.1.1`

**Comment by inyono** [comment]
Please don't close issues before the commits that resolve them are merged into master. You can automate this by including "Close #126" in your commit message. Then GitHub will automatically close the issue after merge.
Also: please open a PR for everything that is done / deployable.
