### ISSUE TITLE
Review mcrypt_decrypt

### ISSUE THREAD

**Issue by inyono** [serlo/serlo.org#13]
Seems like `mcrypt_decrypt` is deprecated and doesn't work right now (e.g. when using the debugger).

**Comment by Knorrke** [comment]
It's deprecated on php v7.1.0 and removed in 7.2.0, aren't we using 7.0.x atm? https://www.php.net/manual/en/function.mcrypt-decrypt.php

apparently we can use `openssl_encrypt` and `openssl_decrypt` instead. https://php.net/manual/en/function.mcrypt-encrypt.php#117667

**Comment by inyono** [comment]
See #14
