### ISSUE TITLE
jQuery is included twice in main.js

### ISSUE THREAD

**Issue by elbotho** [serlo/serlo.org#130]
[Current version ](https://packages.serlo.org/serlo-org-client@5/main.js) includes jQuery twice.

Steps to reproduce:
1: open https://packages.serlo.org/serlo-org-client@5/main.js
2: search for “jQuery JavaScript Library v3.4.1”
3: occurs twice

I checked, it's actually the same code.

@inyono suggests to use the webpack bundle analyzer.

**Comment by kulla** [comment]
Should not be an issue in the new design. Thus, I close this issue.
