### ISSUE TITLE
Chunk hashes don't match

### ISSUE THREAD

**Issue by inyono** [serlo/serlo.org#131]
Currently, we build the nextjs stuff twice. Once on server-side in docker, once client-side for the CDN deployment of the assets. Somehow, the hashes of chunks don't match, though. Can we remove the hashes altogether since the version is in the URL anyways?

**Comment by inyono** [comment]
Another possibility: single `next build`. This probably means, we have to deploy the assets from the docker image directly...

**Comment by Entkenntnis** [comment]
fixed by #132
