### ISSUE TITLE
How shall we address HTML for e2e testing?

### ISSUE THREAD

**Issue by kulla** [serlo/serlo.org#147]
There are several ways to query for HTML elements in e2e testing. Which one shall we use?

* CSS selectors (like `article > section p`)
    * Pro: We do not have to change our HTML in order to use them
    * Contra: They might be fragile. Every time we change the HTML we have to change the selectors (https://stackoverflow.com/a/5821986 ) 
* XPath (similar to CSS selectors)
    * similar to `CSS`
* IDs (give HTML elements IDs like `id="title"` and address them directly)
    * Pro: We can change / rearange our HTML without breaking the tests
    * Pro: Good IDs show the semantics of an HTML element
    * Contra: Same ID can only be used for a singleton HTML element on a page
    * Contra: It is not clear whether an ID is used for testing, styling or inside a script -> Legacy IDs might not be deleted because of this
* Special `data-` attribute like `data-testing-id` (similar to the way with IDs)
    * Pro: It is clear where the ID is used for
    * Pro: Advantages of IDs + it's also possible using the same ID on multiple elements
    * Contra: Adds noise to our HTML
* using the https://schema.org specification
    * Pro: Tests our schema.org specification also
    * Contra: Not always possible

What is your option? In which cases would you use which way? My opinion:

1. Schema.org and IDs when possible (do not add them just for testing)
2. Use a `data-testing-id` attribute as a backup when 1) does not work
3. Avoid nested CSS selectors

**Comment by inyono** [comment]
IMHO: https://github.com/testing-library/react-testing-library#guiding-principles / https://testing-library.com/docs/dom-testing-library/api-queries. So avoid any additional changes to DOM where possible and rather query via the content (best option). If not possible, use some CSS selectors. If also not possible, add `data-testid`.

**Comment by kulla** [comment]
#172 is the follow up issue tracking the implementation of this question
