### ISSUE TITLE
frontend: handle secrets

### ISSUE THREAD

**Issue by inyono** [serlo/serlo.org#178]
- [ ] frontend: Add env variable for secret
- [ ] frontend: Check if `props['secret']` matches that env variable
- [ ] server: add secret to config
- [ ] server: add secret to passed props (currently, it is hardcoded as `secret`)

**Comment by Entkenntnis** [comment]
Do you think we need a secret? I remember you said it would be unnecessary so I've removed most of the stuff related to it.

**Comment by inyono** [comment]
You're right... Forgot that the server isn't even exposed (only the assets are)
