### ISSUE TITLE
Injections via language-versions

### ISSUE THREAD

**Issue by jakobwes** [serlo/serlo.org#183]
Injection of a german-content in for example the English language-version doesn't work in the new editor and are only understood as links in the old one.

**Comment by kulla** [comment]
Why do you need this? What is the use case for this injections?

**Comment by jakobwes** [comment]
The use-case where we stumbled upon this is to try to embed examples for good content from de.serlo.org in the english-page. Also it can be extremely precious for interlanguage-cooperation (from cases where editors in different language-versions work together on content synchronized, to language-learning,...), so it would be a very good improvement for our work

**Comment by kulla** [comment]
Moved to https://docs.google.com/document/d/1rSkFo2JtsSwHHsbosQcgAN4EzeePXLnqi_eCFpUM3u4/edit#heading=h.44s97rl5xddk of the new document with feature requests
