### ISSUE TITLE
Sometimes can't create /serlo pages on other language-tenants

### ISSUE THREAD

**Issue by jakobwes** [serlo/serlo.org#184]
For example if we try in the tamil-tenant (ta.serlo.org) to create the site with the url "serlo" it only creates a/the site with the url "serlo-[id of this page]"

**Comment by Knorrke** [comment]
most probably this is due to a trashed page with the url "serlo" in the specific tennant. I can't access the recycle bin at the moment (#193), so I can't check this.

**Comment by inyono** [comment]
It is as @Knorrke said. There was already an alias "serlo" on ta.serlo.org (most likely a page that got deleted for some reason). I removed the alias manually, you should now be able to change the url to "serlo".
