### ISSUE TITLE
Alias can't be reused

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/serlo.org#199]
1. Create a taxonomy, e.g. schätzen

2. Something goes wrong, so you remove your entry and rename it, e.g. schätzen-verkackt

3. You create a new taxonomy with the same name - now the link looks like: https://de.serlo.org/mathe/deutschland/serlo-lehrplan/5.-klasse/nat%C3%BCrliche-zahlen/sch%C3%A4tzen/-148332

4. The old link is still bound to the entry created in (1): https://de.serlo.org/mathe/deutschland/serlo-lehrplan/5.-klasse/nat%C3%BCrliche-zahlen/sch%C3%A4tzen

*Issue*

I would like to reuse the original link when the existing taxonomy is trashed

**Comment by inyono** [comment]
Proposal:
- Aliases can be marked as `purgeable`
- When checking if an alias is free, you may also use one that is `purgeable`.
- When an entity gets trashed, mark the alias as `purgeable`. When it gets restored, remove the `purgeable` flag if the alias is still in use by the same entity. If not, create a new alias.
- When generating a new alias for an entity (i.e. after renaming), mark the previous alias as `purgeable`.

**Comment by inyono** [comment]
Resolved by #540 (needs some more testing before it goes to production).
