### ISSUE TITLE
frontend: injections don't work in legacy-content

### ISSUE THREAD

**Issue by inyono** [serlo/serlo.org#201]
See https://de.serlo-development.dev/mathe

Injections aren't shown and console throws error because of fonts:
```
downloadable font: download failed (font-family: "Karmilla" style:normal weight:400 stretch:100 src index:1): status=2147746065 source: https://de.serlo-development.dev/karmilla-regular.woff
```

Feature flags:
```
['client-frontend' => true, 'donation-banner' => true, 'frontend-content' => true, 'frontend-diff' => true, 'frontend-donation-banner' => true, 'frontend-editor' => true, 'frontend-footer' => true, 'frontend-legacy-content' => true, 'key-value-store' => true]
```

**Comment by inyono** [comment]
Also doesn't work in staging: https://de.serlo-staging.dev/mathe
This time, the font download error isn't shown (since the footer isn't active and therefore doesn't load global styles).

Feature flags:
```
['client-frontend' => true, 'donation-banner' => true, 'frontend-content' => true, 'frontend-diff' => true, 'frontend-donation-banner' => true, 'frontend-editor' => true, 'frontend-footer' => true, 'frontend-legacy-content' => true, 'key-value-store' => true]
```

**Comment by Entkenntnis** [comment]
The fonts error is strange, but may be unrelated to injections ...

Looking at the dev tools I see three ajax request made for each exercise, and the images are loaded, but when react renders the page client side, this would probably remove the injections from DOM again.

Proposal: Allow nextjs to render a page as static HTML and don't include any frontend javascript.

**Comment by Entkenntnis** [comment]
I'll try to make a PR for this ...

**Comment by Entkenntnis** [comment]
See #224
