### ISSUE TITLE
serlo.org: Community Drop Down on mobile not working

### ISSUE THREAD

**Issue by kathongi** [serlo/serlo.org#203]
Community drop down button on mobile doesn't work on mobile (Browser: chrome, firefox). Click on the community button in navigation doesn't open the drop down options.

**Comment by kathongi** [comment]
![20200113_112109](https://user-images.githubusercontent.com/44167220/72248257-07aa0a80-35f7-11ea-941b-07a427eb6c64.gif)

**Comment by kulla** [comment]
Works with the new design...
