### ISSUE TITLE
Invalid RSS Feed items

### ISSUE THREAD

**Issue by inyono** [serlo/serlo.org#208]
reported by @getjack

> The items of your RSS feeds seem to be invalid. I tried to open your feed https://de.serlo.org/entity/api/rss/article/5/feed.rss with Firefox 46 which did not display the links of your content. I then had a look at the xml and saw that in your property the links have no valid URL but relative paths.
> 
> Please see the result for your self https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fde.serlo.org%2Fentity%2Fapi%2Frss%2Farticle%2F5%2Ffeed.rss
> 
> If you look up the specification of RSS https://validator.w3.org/feed/docs/rss2.html#hrelementsOfLtitemgt you will see that items require a URL and a path is not a valid URL according to https://www.ietf.org/rfc/rfc3986.txt

**Comment by CarolinJaser** [comment]
Included in the list of improvements of the content api
