### ISSUE TITLE
What shall we do with old blogs?

### ISSUE THREAD

**Issue by simonkoehl** [serlo/serlo.org#209]
We have three blogs at serlo.org: https://de.serlo.org/blog

But we want to combine the different topics in one blog.

Can you please merge the blogs and copy the postst from https://de.serlo.org/dev-blog/ and from https://de.serlo.org/mathematik-blog/ to the main blog: https://de.serlo.org/blog/
(we can do the copying manualy, if you want?)

I also think we can reduce this unnecessary complicated structure and have just one /blog per language tenant (that was originally my fault, sorry)

**Comment by kulla** [comment]
Answer: Blog feature will be deleted: #321
