### ISSUE TITLE
Place collapsible (e.g. hint) directly behind link to open them

### ISSUE THREAD

**Issue by Knorrke** [serlo/serlo.org#212]
Currently, when you have opened a hint on an exercise and then open the solution, you don't notice that it actually has opened. Proposed solution is ~to scroll to the opened element.~

~We already implemented this in serlo/athene2#174 but there were some bugs (see serlo/athene2#402) so we removed it in serlo/athene2#417.
Maybe take a look at the jquery scrollTo plugin: https://github.com/flesler/jquery.scrollTo~

**Comment by Knorrke** [comment]
Update: Preferred solution is to just place the hints after "Show hint", instead of the current position:
![grafik](https://user-images.githubusercontent.com/11499926/72256707-19e17400-360a-11ea-9ff1-c7c69649ee24.png)

**Comment by kulla** [comment]
Hints have been removed from exercises in the meanwhile...
