### ISSUE TITLE
Navigation: use curriculum topics for breadcrumbs

### ISSUE THREAD

**Issue by Knorrke** [serlo/serlo.org#213]
>Navigation: Lehrplan vs. Themengliederung 
>
>Aus der Gliederung für einen Lehrplan kann ich auf einen Artikel klicken, der im Inhaltsverzeichnis für Themen aufgehängt ist. Beim Sprung vom Lehrplan in einen Artikel geht die Information verloren in welchem Lehrplan ich war.
>
>So kommt man zwar leicht vom Lehrplan zu einem Artikel, aber zurück geht nichts mehr. Für den nächsten Punkt im Lehrplan muss man wieder durch den ganzen Lehrplan navigieren. 

questions: how to do this with caching? What happens when following links in the article?

**Comment by kulla** [comment]
duplicate of https://github.com/serlo/serlo.org/issues/549
