### ISSUE TITLE
Full subject navigation

### ISSUE THREAD

**Issue by mik-de** [serlo/serlo.org#214]
The subject hierarchy of serlo is deep. Often one sees three dots in subject bar (id="subject-nav"). My recommendation is to provide a pull-menu to see full navigation branch to subject.

This improves context awareness and thus improves didactics.

**Comment by kulla** [comment]
Seems so be solved in the new design:

![2020-05-12-173208_620x363_scrot](https://user-images.githubusercontent.com/1327215/81713754-8fedce80-9476-11ea-846e-e72f3480b3fe.png)

Reopen this issue when you think it is still relevant...
