### ISSUE TITLE
extend content "sharing" functionalities

### ISSUE THREAD

**Issue by simonkoehl** [serlo/serlo.org#215]
At the moment, sharing functionalities are in the content sub menu "teilen"

Let's include:
- Google Classroom
- Facebook
- Twitter
- Mail

And may be, we should replace the sharing functionalities. E.g. like in Khan Academy (below the head line) : https://www.khanacademy.org/math/trigonometry/trig-with-general-triangles/solving-general-triangles/a/laws-of-sines-and-cosines-review

**Comment by elbotho** [comment]
@simonkoehl this issue is outdated with the new design, right?

**Comment by CarolinJaser** [comment]
This issue is outdated, since it was already implemented in the new design.
