### ISSUE TITLE
e2e: add tests for every content type and important page

### ISSUE THREAD

**Issue by inyono** [serlo/serlo.org#222]
Add tests for the following combinations:
- All content types + taxonomy term + user profile
- created with legacy editor + created with editor
- rendering + editing
- legacy stack + frontend

**Comment by kulla** [comment]
Issues for the login process:

- [ ] Logging in with wrong password fails
- [ ] Logging in with wrong user name fails
- [ ] Logout process, e.g:
    - given I am logged in as `user`
    - given I am on page `page`
    - when I click on button `Abmelden`
    - then I am on page `page`
    - then I am logged out (e.g. button `Anmelden` for `login` occurs and we cannot open `/users/me`)

**Comment by kulla** [comment]
Issues for testing taxonomies:

- [ ] view taxonomy with subtopics
- [ ] view taxonomy with subentities and topic folders
- [ ] navigating through taxonomies
- [ ] create new subtopic
- [ ] create new subtopic folder
- [ ] update term or description of topic / topic folder

Backlog:

- order taxonomy terms

**Comment by Knorrke** [comment]
For #182 we need the following tests:
- [ ] Create and save a new entitie of each type (article, video, exercise, ...)
- [ ] Edit Taxonomy
- [ ] Edit an legacy-entitie and check if the convert worked (e.g. check if the content is still there)

**Comment by kulla** [comment]
@pazaan @Knorrke I have merged `feature/e2e-tests` into `feature/active-edtr-io` so that we can implement the tests for the new editor. `feature/e2e-tests` is deleted and from now on we work on `feature/active-edtr-io`.

**Comment by kulla** [comment]
Backlog:

- [ ] updating entity types (video, article, course...)
