### ISSUE TITLE
Remove automatic checkout for reviewers in old editor

### ISSUE THREAD

**Issue by kulla** [serlo/serlo.org#223]
Follow up of #220 and #221: Currently the automatic checkout seems only to be removed in the new editor. @Knorrke  Is this the intended implementation?

**Comment by inyono** [comment]
Pretty sure this is intended because the reason for the auto-checkout was that the workflow in the old editor was annoying af.

**Comment by Knorrke** [comment]
Yes, also seeing that #182 should be finished soon, I think it is fine to include the feature in the new editor only.
