### ISSUE TITLE
frontend: injections created with the new editor don't work in legacy-content

### ISSUE THREAD

**Issue by inyono** [serlo/serlo.org#224]
See https://de.serlo-staging.dev/mathe, the first exercise was created with the new editor. You can't select any of the answers, though.

Btw: might also be a problem in the legacy-editor-renderer, not sure.

**Comment by Entkenntnis** [comment]
Probably related to nextjs is not hydrating injections

**Comment by Knorrke** [comment]
atm hydrating is done by triggering the init method of  `client` here: https://github.com/serlo/serlo.org/blob/7e952731c84befff76e252c315c3cc86b3faa082/packages/public/frontend/src/edtr-io/plugins/injection.tsx#L63

Don't know if this is working in frontend

**Comment by Entkenntnis** [comment]
See #230
