### ISSUE TITLE
Rendering issue at https://de.serlo.org/user/profile/julianBabl

### ISSUE THREAD

**Issue by kulla** [serlo/serlo.org#226]
Issue:

![2020-01-14-155153_1045x295_scrot](https://user-images.githubusercontent.com/1327215/72354414-0277b900-36e6-11ea-8fd8-fa622efdaff4.png)

There should be a spoiler at this place. The web console prints the error

```
Error: "Expected `string` for `language`, got `undefined`"
     at /vendors~react-syntax-highlighter/refractor-core-import.0cf631db.js:1 7.0.1
```

**Comment by inyono** [comment]
This was a hint which isn’t even activated in profiles and could only be created via a bug we had. Just delete the node and re-add a spoiler

**Comment by kulla** [comment]
Thanks!
