### ISSUE TITLE
anchor with new edtr.io plugin jumps a little bit too far 

### ISSUE THREAD

**Issue by metzgaria** [serlo/serlo.org#238]
example: [Serlo Profile](https://de.serlo.org/user/profile/metzgaria)
(anchor is set before the headings)
(@Knorrke said it's only a serlo issue, was fixed with CSS in old editor)

**Comment by Knorrke** [comment]
It does jump to the correct position, but we have the fixed breadcrumbs bar hiding it, so we want to adjust this. We have a fix for this with some `:target` pseudo-element...

**Comment by kulla** [comment]
Duplicate of #389
