### ISSUE TITLE
https://en.serlo.org/event/history broken

### ISSUE THREAD

**Issue by kulla** [serlo/serlo.org#242]
![2020-01-22-012037_978x468_scrot](https://user-images.githubusercontent.com/1327215/72854738-8963fd00-3cb5-11ea-9df9-8158d2560965.png)

**Comment by inyono** [comment]
Probably #229

**Comment by Knorrke** [comment]
The first sentry issue is directly of the route en.serlo.org/event/history, the second the user profile of @jakobwes which seems to be the same broken log entry. The third issue is a bit weird, because it's the same error, but the pages are working...

**Comment by inyono** [comment]
Closed with #239
