### ISSUE TITLE
Email notification of other tenants have wrong links

### ISSUE THREAD

**Issue by Knorrke** [serlo/serlo.org#249]
e.g. email contains link `https://www.serlo.org/entity/view/41648` which redirects to `de.` instead of `en.`

Interestingly `https://www.serlo.org/41648` works, as `https://de.serlo.org/41648` tries to resolve the correct instance

**Comment by kulla** [comment]
Will be fixed by implementing https://github.com/serlo/api.serlo.org/issues/143
