### ISSUE TITLE
Set "cursor:zoom-in;" for images inside the content of an article

### ISSUE THREAD

**Issue by Knorrke** [serlo/serlo.org#253]
(cc Nish): The magnification effect on images (when clicking) is not noticable for users.

Maybe change the Pointer to a magnifying glass?

**Comment by kulla** [comment]
The CSS `cursor:zoom-in;` can be used here.

**Comment by Knorrke** [comment]
The image plugin itself doesn't implement the magnifying so it's a bit strange to change it there...

**Comment by kulla** [comment]
Okay, then this can be closed... :-)
