### ISSUE TITLE
caching on landing page breaks with feedback/flasher

### ISSUE THREAD

**Issue by Knorrke** [serlo/serlo.org#259]
The landing page is cached (and obviously should be), but for an logged out user no flashers are shown because of this. As @arekkas said: A resolution could be to have a dedicated success page.
But a solution has to adress the following different user actions:

- Sign up (old issue: serlo/athene2#477)
- Forgot Password (old issue: serlo/athene2#281)
- Account Activation (old issues: serlo/athene2#615, serlo/athene2#612 )

**Comment by kulla** [comment]
Since this only affects legacy serlo.org I close this issue (new design should not be affected).
