### ISSUE TITLE
empty course has no ui

### ISSUE THREAD

**Issue by simonkoehl** [serlo/serlo.org#260]
https://de.serlo.org/community/neue-faecher-themen/medienbildung/datensammlung-big-data-ist-big-data

This happens with every course from https://de.serlo.org/community/neue-faecher-themen/medienbildung/datensammlung-big-data

Other courses on serlo.org seem to be fine: https://de.serlo.org/61911/uebersicht

![course view broken](https://user-images.githubusercontent.com/3379377/40252344-64822b86-5adc-11e8-997f-876bac1e3088.PNG)

**Comment by kulla** [comment]
#292 is a fix for this issue (The error message is changed for courses):

![2020-02-05-162850_1204x524_scrot](https://user-images.githubusercontent.com/1327215/73855782-d955ce80-4834-11ea-9cc1-37ab5587b7c4.png)

With the new editor this situation should normally not occur often, though...
