### ISSUE TITLE
Timeago shouldn't label datetimes in the future

### ISSUE THREAD

**Issue by inyono** [serlo/serlo.org#261]
Probably fixed by taking the "minimum" of datetime from database and "now", see e.g. 

<img width="604" alt="Screen Shot 2019-06-04 at 15 56 58" src="https://user-images.githubusercontent.com/1508477/58884921-91990900-86e1-11e9-8747-1c745f44c5d5.png">

**Comment by kulla** [comment]
Should be fixed in the new design. Please reopen it, when it is still relevant...
