### ISSUE TITLE
Don't create a new entity until we have a first revision

### ISSUE THREAD

**Issue by inyono** [serlo/serlo.org#263]
To reproduce: create new article, you see the created uuid in the URL, close tab without saving the revision => We have an article without a revision. We should fix that and delete dead nodes that still exist.

**Comment by inyono** [comment]
Fixed with Edtr.io, @Knorrke?

**Comment by Knorrke** [comment]
No, this is only handled for subentities for the moment. I didn't find a good way to do this for the top level entity. I don't remember details, but it had something to do with the order of creating the revisions and entities... Something like: we want to create the childs first, but they already need the parent to exist...

**Comment by inyono** [comment]
Should look into this again, might also be related to #460.

**Comment by CarolinJaser** [comment]
Since this cannot currently be fixed in the legacy system and can only be fixed once the new system is up and running we are closing this for now
