### ISSUE TITLE
Ignore trailing slashes

### ISSUE THREAD

**Issue by elbotho** [serlo/serlo.org#267]
@Knorrke suggested to always ignore trailing slashes in the urls.
We need to check first which pages that rely on that trailing slash to display different pages.
(e.g. `mathe/` )

**Current example**
https://de.serlo.org/nachhaltigkeit/ should redirect to https://de.serlo.org/nachhaltigkeit
instead it displays "Page not found".

**Comment by elbotho** [comment]
currently working in new frontend, so can probably be closed.

**Comment by kulla** [comment]
@elbotho Indeed :+1:
