### ISSUE TITLE
Prevent Search engines indexing pages including API params

### ISSUE THREAD

**Issue by Knorrke** [serlo/serlo.org#274]
E.g. Google linked to the article "Zentrische Streckung (Konstruktion)" with included `?hideBreadcrumbs` api parameter. These are only for embedding serlo via iframe and should not be set when accessing the site directly from google (e.g. because editing functionality is not visible otherwise).

**Comment by kulla** [comment]
We can set a canonical link element ( https://en.wikipedia.org/wiki/Canonical_link_element ) which should solve this issue.

**Comment by inyono** [comment]
Fixed. Links with query params should be removed from Google's index next time their crawler checks the sites.
