### ISSUE TITLE
Error when adding two math formulas

### ISSUE THREAD

**Issue by kulla** [serlo/serlo.org#281]
Steps for reproducing the bug

1. Open an article with the new editor
2. Add a formula
3. Return to the text and add a new formula

Bug: No new formula window opens and we get the error message `Error: `Node.assertNode` could not find node with path or key: List [ 0, 1, 3 ]`

Video:

![bug](https://user-images.githubusercontent.com/1327215/73457433-f4779880-4373-11ea-80c6-b2e7c6abc484.gif)

**Comment by inyono** [comment]
upstream: https://github.com/edtr-io/edtr-io/issues/292
