### ISSUE TITLE
Deactivate math-puzzle for all subjects that are not math

### ISSUE THREAD

**Issue by inyono** [serlo/serlo.org#284]

**Comment by Knorrke** [comment]
I think the only one (other than math) that does allow math puzzles is Community, and its debatable if we want it there since we have a playground for new content there.... But we can turn it off there as well. Its handled in the subjects config

**Comment by kulla** [comment]
Besides "boîte à méthodes" and "nouvelles matières" the math puzzle is only allowed in community / test area next to the math area. -> I have asked whether this is intened.

@inyono Do you want to deactivate the math puzzle also in the community area? (We can discuss this in the next meeting)

**Comment by kulla** [comment]
- [ ] In nouvelles matières could be (it means new topics, so could be mathematics-related) but in boîte à méthodes the puzzle is not useful and shouldn't be allowed :)"
- [ ] Deactivate in Community / Testbereich iff there is already a math subject
