### ISSUE TITLE
Solution of new editor have two "Show solution" buttons

### ISSUE THREAD

**Issue by kulla** [serlo/serlo.org#288]
Steps to reproduce: Create an exercise with the new editor with a solution. When viewing the exercise clicking "Show solution" would show another element "Lösung anzeigen" which need to be clicked so that the solution gets visible:

![2020-02-04-153352_211x198_scrot](https://user-images.githubusercontent.com/1327215/73754142-36ce1a80-4764-11ea-9bd9-bc43c8d6d3cd.png)

**Comment by inyono** [comment]
Are you sure you are up-to-date with master? This looks like a duplicate of #283 which has been fixed in #286.

**Comment by kulla** [comment]
Thx. I'll checkout master. Should be the same issue...

**Comment by inyono** [comment]
See e.g. https://de.serlo.org/3059
