### ISSUE TITLE
Error messages when login fails are still in German

### ISSUE THREAD

**Issue by jakobwes** [serlo/serlo.org#31]
The error-messages when during login (like "Mit dieser Kombination ist bei uns kein Benutzer registriert.") are also in other language-versions still in german. I think this text-output should also be given by Crowdin, so that the message is in the respective language.
Function that gives the output/code-line: https://github.com/serlo/serlo.org/blob/0269019e8e00d29d0cbfa3e3994da204b30f4214/packages/public/server/src/module/Authentication/src/Authentication/Adapter/UserAuthAdapter.php#L102).

**Comment by Knorrke** [comment]
What.... How?^^ i looked at this code several times already and didn't notice
