### ISSUE TITLE
Automatic Checkout in the sandbox

### ISSUE THREAD

**Issue by yolo-bird** [serlo/serlo.org#312]
New authors should have a place where they can test editing without waiting for their review. 

Edits in de.serlo.org/community/sandkasten and in children taxonomy terms should be checked out automatically. (this issue is only relevant for the german sandbox)

**Comment by simonkoehl** [comment]
I have a bad feeling with such "hacks".

among other problems:
- authors learn an unrealistic workflow
- unwanted influence on reviewing stats?

May be there is a better solution.

**Comment by yolo-bird** [comment]
Interestingly a place where authors can write content that is live visible immediately is one of the most asked feature request. Especially when new to editor or in time trouble as you want to create something for your students for the next day. 

So the question for me is: where can this place be: 

I see to options (does somebody see other options?)
- the profile
- the sandbox

Both have the advantage that there is a clear distinction between the "main body" of Serlo and some test private space. 

I think the sandbox is the quicker solution and a good way to see how authors will react to this new possibility. Also it might inspire a new way of editing. People work on their own branches and can merge (=copy) them into the main part. 

Self reviews do not count for the reviewing stats, so this would not be a problem.

**Comment by simonkoehl** [comment]
I am sure, there is a way to adress this more systematically and withou adding new functionality. We need better ideas

**Comment by kulla** [comment]
@yolo-bird I have implemented the functionality in #435 which is ready to be merged. However since there seems to be concerns about this implementation I will hold back the deployment. Please tell me when it is certain how I shall continue...

**Comment by simonkoehl** [comment]
This issue needs some basic product management pls. 

1. define problem
2. collect possible solutions
3. discuss possibilitites and decide

And in general @yolo-bird and @kulla pls be very sceptical with such kind of hacks - this generates divers follow up problems and technical debt

**Comment by inyono** [comment]
In this specific case, I wouldn't be too concerned regarding hacks / technical debt because
- It doesn't touch the database at all
- It is a small change that is also documented (easy to remove later again)

We could use this implementation as a prototype, i.e.
- Check how users use the sandbox and review potential use cases (new subjects, whatever) and potential problems
- If this is something our users want, we can later implement that in a better way
- If it is something that isn't used in a good way / problems arise / whatever, we can easily remove the feature again.

**Comment by kulla** [comment]
@yolo-bird Let's discuss this tomorrow...
