### ISSUE TITLE
Review best practices for email sending

### ISSUE THREAD

**Issue by inyono** [serlo/serlo.org#314]
We observer issues in delivering emails especially to GMX and Web.de addresses. We should review:
- https://postmaster.gmx.net/en/best-practice
- https://postmaster.web.de/en/best-practice

**Comment by kulla** [comment]
Actually we have to check the list at https://www.gmx.net/mail/senderguidelines/ (or at https://web.de/email/senderguidelines/ with the same content):


- [ ]    Make sure that your mail server and client time and date are correctly set as specified in RFC 5322.
- [ ]    Ensure that the following email headers included in your message are syntactically correct: Date, From, Sender, To.
- [ ]    Make sure that the following headers included in your email are limited to just one each: BCC, CC, Date, From, Sender, Subject, To.
- [ ]    Immediately remove hard bounced email addresses from your mailing list.
- [ ]    Make sure your mail server has a static IP address.
- [ ]    Ensure you have valid DNS records of your domain pointing to your IP address and valid reverse DNS records of your IP address pointing to your domain. You can check your DNS configuration here.
- [ ]    Verify that your domain has a properly configured MX or A record. You can check your MX configuration here.
- [ ]    Ensure your email server always sends a valid HELO/EHLO value (the fully-qualified domain name) as specified in RFC 5321. You can check your HELO here.
- [ ]    Verify that your mail server IPs are not listed on one of the Spamhaus.org lists.

**Comment by kulla** [comment]
For the HELO/EHLO check: I registered a user at de.serlo.org with the email helocheck@abuseat.org (as documented in https://www.abuseat.org/helocheck.html). We got the answer:

```550 *** The HELO for IP address 147.253.222.183 was 'mta-222-183.sparkpostmail.com' (valid syntax) ***```

Thus it is a valid HELO/EHLO value. The IP address ( https://www.spamhaus.org/query/ip/147.253.222.183 ) nor the domain ( https://www.spamhaus.org/query/domain/mta-222-183.sparkpostmail.com ) is listed at spamhaus.org. The same is true for [mail.serlo.org](https://www.spamhaus.org/query/domain/mail.serlo.org):

![2020-04-10-191658_544x253_scrot](https://user-images.githubusercontent.com/1327215/79009591-240b0400-7b60-11ea-9a8f-eef6e8dcb119.png)
![2020-04-10-191754_451x209_scrot](https://user-images.githubusercontent.com/1327215/79009598-28372180-7b60-11ea-8e09-ca7a18ac358e.png)
![2020-04-10-191920_335x181_scrot](https://user-images.githubusercontent.com/1327215/79009614-3127f300-7b60-11ea-98c8-44e7e63975c1.png)

**Comment by kulla** [comment]
The domain `mta-222-183.sparkpostmail.com` has a valid [rDNS](https://en.wikipedia.org/wiki/Reverse_DNS_lookup) entry:

![2020-04-10-192139_716x389_scrot](https://user-images.githubusercontent.com/1327215/79009767-9976d480-7b60-11ea-8d5c-12aebd5e571d.png)

I am not sure whether the same needs to hold for `mail.serlo.org`. When I read https://web.de/email/senderguidelines/ correctly than this needs only to be true for the sending mta (in this case the sparkpost mail server).

**Comment by kulla** [comment]
My current lead: I noticed that mails from `community.serlo.org` can be send to `web.de` or `gmx.de`. Thus I think it might be a wrongly formatted mail...

**Comment by kulla** [comment]
I have investigated the mail for activating an account.

### Problems with the mail:

- [ ] There is an empty `Sender:` header

### Errors from validation tool
The tool https://tools.ietf.org/tools/msglint/ gives the following error message:

```
-----------
UNKNOWN: unknown header 'X-Original-To' at line 2
UNKNOWN: unknown header 'Delivered-To' at line 3
WARNING: line too long in header 'Received:' at line 4
WARNING: nested comments unwise in header 'Received' at lines 4-8
WARNING: line too long in header 'Received:' at line 9
WARNING: nested comments unwise in header 'Received' at lines 9-13
UNKNOWN: unknown header 'DKIM-Signature' at lines 14-20
UNKNOWN: unknown header 'X-MSFBL' at lines 21-24
WARNING: line too long in header 'Authentication-Results:' at line 25
UNKNOWN: unknown header 'Authentication-Results' at line 25
WARNING: line too long in header 'Received:' at line 26
WARNING: nested comments unwise in header 'Received' at lines 26-29
ERROR: empty header 'Sender' at line 38
WARNING: line too long in header 'List-Unsubscribe:' at line 39
ERROR: expected '>' and saw token ':' in header 'List-Unsubscribe' at line 39
ERROR: unexpected tokens at end of header 'List-Unsubscribe' at line 39
ERROR:  Token type          atom: mZL........zk5ZjQiIH0~
ERROR:  Token type       special: >
ERROR: expected phrase at token '<' in header 'List-Id' at line 40
OK: found part multipart/alternative line 42
OK: preamble 42: 
OK: preamble 43: This is a message in Mime Format.  If you see this, your 
    mail reader does not support this format.
OK: preamble 44: 
ERROR: mismatch between inner content-transfer-encoding and that of enclosing 
       multipart, line 49
OK: found part text/html line 49
ERROR: mismatch between inner content-transfer-encoding and that of enclosing 
       multipart, line 66
OK: found part text/plain line 66
ERROR: Content-Transfer-Encoding doesn't permit 8-bit characters in body 
       ending line 78
-----------
```

### Example email

```
Return-Path: <bounces@mail.serlo.org>
X-Original-To: xyz@example.org
Delivered-To: xyz@example.org
Received: from example.org
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=mail.serlo.org;
	s=scph0919; t=11111111; i=@mail.serlo.org;
	bh=...;
	h=Date:Message-ID:From:To:Subject:Content-Type;
	b=....
Authentication-Results:  ac.mta3vsmtp.cc.prd.sparkpost smtp.user=<hidden>; auth=pass (LOGIN)
Received: from [0.0.0.0] ([0.0.0.0:52622] helo=smtp.eu.sparkpostmail.com)
	by ac.mta3vsmtp.cc.prd.sparkpost (envelope-from <notifications@mail.serlo.org>)
	(ecelerity 4.3.0.69089 r(Core:4.3.0.45)) with ESMTPA
	id 99.4F.00000.AAAAAAED5; Fri, 06 Dec 2019 16:02:19 +0000
Date: Fri, 06 Dec 2019 17:02:19 +0100
Message-ID: <99.4F.00000.AAAAAAED5@ac.mta3vsmtp.cc.prd.sparkpost>
From: notifications@mail.serlo.org
To: xyz@example.org
Subject: =?UTF-8?Q?Bitte=20aktiviere=20deinen=20Account=20auf=20Serlo!=0A?=
MIME-Version: 1.0
Content-Type: multipart/alternative;
 boundary="=_597585c6ca62d9a588ce9eb3a29217c9"
Sender: 
List-Unsubscribe: <mailto:unsubscribe@eu.sparkpostmail.com?subject=unsubscribe:mZLXZYXdBWwYs6auay2MJ-UQVPKkLhAirj5YLQ7gUwg~|eyAicmNwdF90byI6ICJ0ZXN0X2t1bGxhLm1haWxAa3VsbGEubWUiLCAidGVuYW50X2lkIjogInNwY2V1IiwgIm2JlYTVkNTkwYzk5ZjQiIH0~>
List-Id: <spceu.9112.0.sparkpostmail.com>

This is a message in Mime Format.  If you see this, your mail reader does not support this format.

--=_597585c6ca62d9a588ce9eb3a29217c9
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: 8bit

    Hallo XYC,<br />
<br />
 Danke für deine Registrierung auf Serlo.<br />
<br />
 Bitte bestätige deinen Account, indem du auf den folgenden Link klickst:<br />
     <a href="http://de.serlo.org/auth/activate/">Account freischalten</a><br />
<br />
<br />
 Wir freuen uns auf deinen Beitrag für Serlo!<br />
<br />
Dein Community-Support

--=_597585c6ca62d9a588ce9eb3a29217c9
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

    Hallo XYZ,

 Danke für deine Registrierung auf Serlo.

 Bitte bestätige deinen Account, indem du auf den folgenden Link klickst:
 http://de.serlo.org/auth/activate/abc

 Wir freuen uns auf deinen Beitrag für Serlo!

Dein Community-Support

--=_597585c6ca62d9a588ce9eb3a29217c9--
```

**Comment by kulla** [comment]
@inyono I noticed that in the DNS entry of serlo.org there is still a gmail address for handling the mail registered:

```
▶ host serlo.org
serlo.org has address 104.26.15.71
serlo.org has address 104.26.14.71
serlo.org has IPv6 address 2606:4700:20::681a:f47
serlo.org has IPv6 address 2606:4700:20::681a:e47
serlo.org mail is handled by 1 aspmx.l.google.com.
serlo.org mail is handled by 5 alt1.aspmx.l.google.com.
serlo.org mail is handled by 5 alt2.aspmx.l.google.com.
serlo.org mail is handled by 10 alt3.aspmx.l.google.com.
serlo.org mail is handled by 10 alt4.aspmx.l.google.com.
```

Is this still valid or shall we update this entry to `mail.serlo.org`?

**Comment by kulla** [comment]
Follow up of #366 : I noticed that a lot of our emails to gmx.de or web.de get delayed:

![2020-04-15-153929_1121x770_scrot](https://user-images.githubusercontent.com/1327215/79343952-67ce8680-7f2f-11ea-8761-eef874d01fed.png)

The reason for the delay is either that the mail agent cannot be reached (which I guess we cannot fix) or the following reason is given:

![2020-04-15-154036_953x103_scrot](https://user-images.githubusercontent.com/1327215/79344062-964c6180-7f2f-11ea-9b80-31ad14868c54.png)

Lets have a look on this issue and lets discuss it at our next meeting.

**Comment by inyono** [comment]
> @inyono I noticed that in the DNS entry of serlo.org there is still a gmail address for handling the mail registered:
> 
> ```
> ▶ host serlo.org
> serlo.org has address 104.26.15.71
> serlo.org has address 104.26.14.71
> serlo.org has IPv6 address 2606:4700:20::681a:f47
> serlo.org has IPv6 address 2606:4700:20::681a:e47
> serlo.org mail is handled by 1 aspmx.l.google.com.
> serlo.org mail is handled by 5 alt1.aspmx.l.google.com.
> serlo.org mail is handled by 5 alt2.aspmx.l.google.com.
> serlo.org mail is handled by 10 alt3.aspmx.l.google.com.
> serlo.org mail is handled by 10 alt4.aspmx.l.google.com.
> ```
> 
> Is this still valid or shall we update this entry to `mail.serlo.org`?

These are for the non-automated mails from e.g. `jonas@serlo.org`

**Comment by inyono** [comment]
> The reason for the delay is either that the mail agent cannot be reached (which I guess we cannot fix) or the following reason is given:
> 
> ![2020-04-15-154036_953x103_scrot](https://user-images.githubusercontent.com/1327215/79344062-964c6180-7f2f-11ea-9b80-31ad14868c54.png)

Well, we are sending all mails together in the night. That aren't many emails, though (if I interpret the Sparkpost Analytics correctly, we are talking about ~50 emails). We could spread them over a longer period (e.g. a timeout after every sent mail) or sent the notifications out more often (e.g. every 6 hours). I don't think that this should be a problem, though, since that is far from mass-emailing what we are doing right now...

**Comment by kulla** [comment]
Since two weeks we almost have no bounces nor delays:

![2020-05-25-160852_1186x344_scrot](https://user-images.githubusercontent.com/1327215/82820257-2328fa00-9ea2-11ea-9ea6-06744b558ea1.png)

Thus I close this issue. Reopen it in case it is still needed...
