### ISSUE TITLE
Add source to Image Plugin

### ISSUE THREAD

**Issue by yolo-bird** [serlo/serlo.org#320]
Enforce that author's name their source when uploading an image. 

Add button: "Eigenes Bild" and "Bildquelle". 
In "Bildquelle" the author has to name the source and/or add the respective url.

**Comment by kulla** [comment]
From #349:

"Zukünftig sollte es bei Bilduploads für Autori*innen verpflichtend sein folgende Daten anzugeben:

* Autor*in
* Bildquelle als URL(falls nicht selbst erstellt)
* Lizenz (falls nicht selbst erstellt; bei selbst erstellten wird sie zu unserer Standardlizenz per default)

Bei der Lizenz bietet sich ein Drop-Down Menu der häufisgten Lizenzen zwecks Nutzerfreundlichkeit an."

**Comment by kulla** [comment]
Note for me: New Pixabay license need to be shown.

**Comment by yolo-bird** [comment]
Already moved to the Trelloboard: https://trello.com/b/M2QlFMxN/serlo-softwarew%C3%BCnsche
