### ISSUE TITLE
"Mini" Plugins?

### ISSUE THREAD

**Issue by kathongi** [serlo/serlo.org#323]
Sometimes when I remove text, there still remains some kind of "mini" plugin which is difficult to delete.

![image](https://user-images.githubusercontent.com/44167220/75430594-d50c6500-594b-11ea-98a5-6ae5940f8c20.png)

other context in which the "mini" plugin appears:
![2020-02-27 09-57-52_Trim](https://user-images.githubusercontent.com/44167220/75430612-db9adc80-594b-11ea-9edf-a0c6739081b8.gif)

**Comment by kathongi** [comment]
https://de.serlo.org/5513 (if someone wants to test it)

**Comment by inyono** [comment]
Settings -> Delete or by using the delete key

**Comment by CarolinJaser** [comment]
In Backlog (https://docs.google.com/document/d/1rSkFo2JtsSwHHsbosQcgAN4EzeePXLnqi_eCFpUM3u4/edit#) verschoben
