### ISSUE TITLE
New Editor: License not shown for not CC-BY-SA licenses

### ISSUE THREAD

**Issue by kulla** [serlo/serlo.org#324]
While saving the license is not shown:

![2020-02-28-154441_646x398_scrot](https://user-images.githubusercontent.com/1327215/75557934-4417b580-5a41-11ea-8ccd-a09d530cb444.png)

**Comment by inyono** [comment]
This only happens for the weird custom licenses because they have no license text.

**Comment by kulla** [comment]
Duplicate of https://github.com/serlo/serlo.org/issues/624 -> see solution there
