### ISSUE TITLE
Bug in /entity/unrevised

### ISSUE THREAD

**Issue by yolo-bird** [serlo/serlo.org#338]
When editing the solution of an exercise, also the indication of the exercise (Aufgabenstellung)  appears in /entity/unrevised. Yet, nothing has been altered in the indication. 

See: https://de.serlo.org/entity/repository/compare/148537/154601
(in fact, in the diff there are same small changes, because there seems to have something happened with the plugins in the backgroud. Yet contentwise the indication is untouched)

**Comment by inyono** [comment]
Working as intended, exercise was still in old format
