### ISSUE TITLE
Enforce indication of source for images

### ISSUE THREAD

**Issue by yolo-bird** [serlo/serlo.org#349]
Zukünftig sollte es bei Bilduploads für Autori*innen verpflichtend sein folgende Daten anzugeben:
- Autor*in
- Bildquelle als URL(falls nicht selbst erstellt) 
- Lizenz (falls nicht selbst erstellt; bei selbst erstellten wird sie zu unserer Standardlizenz per default)

Bei der Lizenz bietet sich ein Drop-Down Menu der häufisgten Lizenzen zwecks Nutzerfreundlichkeit an.

**Comment by kulla** [comment]
Duplicate of #320
