### ISSUE TITLE
Render multiple GeoGebra applets correctly

### ISSUE THREAD

**Issue by inyono** [serlo/serlo.org#350]
There seems to be a problem when multiple GeoGebra applets occur in the same entity, see e.g. https://de.serlo.org/entity/repository/compare/157596/158782. Probably something wrong in the GeoGebra plugin itself (e.g. the "caching")

**Comment by Entkenntnis** [comment]
The frontend port seems not to affected by this: https://github.com/serlo/frontend/blob/master/src/components/content/Geogebra.tsx (caching is disabled)

**Comment by inyono** [comment]
Fixed in https://github.com/edtr-io/edtr-io/commit/f39085bc8bc61fa38c65a28fe008fc699c4c73f9, will be deployed the next time we update Edtr.io
