### ISSUE TITLE
Unable to save with table plugin 

### ISSUE THREAD

**Issue by metzgaria** [serlo/serlo.org#351]
Wanted to add some tables to https://de.serlo.org/entity/repository/compare/160143
It is working  in this edit. 
But this table:
![relevante Tabelle](https://user-images.githubusercontent.com/26926820/78673102-f3b63200-78e1-11ea-9a40-28082ba87585.png)
leads to:
![Fehlermeldung speichern](https://user-images.githubusercontent.com/26926820/78673127-fb75d680-78e1-11ea-841d-04602651f315.png)

state:
```
"{\"plugin\":\"rows\",\"state\":[{\"plugin\":\"text\",\"state\":[{\"type\":\"p\",\"children\":[{\"text\":\"Damit die Eingabe und die Datenhaltung einfacher ist, gibt man bei \"},{\"type\":\"a\",\"href\":\"/69730\",\"children\":[{\"text\":\"Datenbankverwaltungssystemen (DBMS)\"}]},{\"text\":\" zu den Attributen einen Datentyp an. Dadurch werden die Attributwerte auf Korrektheit überprüft und passend formatiert angezeigt.\"}]}]},{\"plugin\":\"text\",\"state\":[{\"type\":\"p\",\"children\":[{\"text\":\"Die Datentypen unterscheiden sich in den verschiedenen DBMS in ihren Bezeichnern, aber die meisten Typen gibt es in allen Systemen. \"}]}]},{\"plugin\":\"text\",\"state\":[{\"type\":\"p\",\"children\":[{\"text\":\"Als Übersicht ist hier eine Auswahl der wichtigsten Datentypen mit einem häufigen Bezeichner.\"}]}]},{\"plugin\":\"text\",\"state\":[{\"type\":\"h\",\"level\":2,\"children\":[{\"text\":\"Text\"}]}]},{\"plugin\":\"table\",\"state\":\"<table>\\n <thead>\\n <tr>\\n <th>Datentyp</th>\\n <th>Aufruf-Format</th>\\n <th>Erläuterung</th>\\n </tr>\\n </thead>\\n <tbody>\\n <tr>\\n <td>VARCHAR</td>\\n <td>VARCHAR(20)</td>\\n <td>Text mit maximal 20 Zeichen</td>\\n </tr>\\n <tr>\\n <td>CHAR</td>\\n <td>CHAR(20)</td>\\n <td>Text mit genau 20 Zeichen. Kürzere Eingaben werden mit Leerzeichen aufgefüllt</td>\\n </tr>\\n </tbody>\\n</table>\"},{\"plugin\":\"text\",\"state\":[{\"type\":\"h\",\"level\":2,\"children\":[{\"text\":\"Zahl\"}]}]},{\"plugin\":\"table\",\"state\":\"<table>\\n <thead>\\n <tr>\\n <th>Datentyp</th>\\n <th>Aufruf-Format</th>\\n <th>Erklärung</th>\\n </tr>\\n </thead>\\n <tbody>\\n <tr>\\n <td>INT</td>\\n <td>INT</td>\\n <td>ganze Zahl mit begrenztem (aber meist ausreichendem) Wertebereich</td>\\n </tr>\\n <tr>\\n <td>DOUBLE</td>\\n <td>DOUBLE</td>\\n <td>Kommazahl mit ungefähr 15 Ziffern</td>\\n </tr>\\n<tr>\\n <td>DECIMAL</td>\\n <td>DECIMAL(3,2)</td>\\n <td>Kommazahl mit 3 Stellen vor dem Komma und zwei dahinter </td>\\n </tr>\\n </tbody>\\n</table>\"},{\"plugin\":\"text\",\"state\":[{\"type\":\"h\",\"level\":2,\"children\":[{\"text\":\"Zeit und Datum\"}]}]},{\"plugin\":\"table\",\"state\":\"<table>\\n <thead>\\n <tr>\\n <th>Datentyp</th>\\n <th>Erklärung</th>\\n </tr>\\n </thead>\\n <tbody>\\n <tr>\\n <td>DATE</td>\\n <td>Akzeptiert eine Datumsangabe</td>\\n </tr>\\n <tr>\\n <td>TIME</td>\\n <td>Akzeptiert eine Zeitangabe</td>\\n </tr>\\n </tbody>\\n</table>\"}]}"
```

POST Error 403 Cloudflare is blocking me

**Comment by inyono** [comment]
This is kinda intended since you shouldn't write HTML. The only supported use case is writing the table via Markdown.

**Comment by metzgaria** [comment]
But this was saved: 
https://de.serlo.org/entity/repository/compare/160143/160486

And I have a second szenario where i am not allowed to save now. Same error. No table plugin used (exercise, only text, images and solution separator)

**Comment by metzgaria** [comment]
And I should be able to save HTML in the code plugin, right?

> 
> 
> This is kinda intended since you shouldn't write HTML. The only supported use case is writing the table via Markdown.

**Comment by metzgaria** [comment]
`` revision/160599":{"plugin":"type-text-exercise","state":{"id":160599,"license":{"id":1,"title":"Dieses Werk steht unter der freien Lizenz CC BY-SA 4.0","url":"https://creativecommons.org/licenses/by-sa/4.0/deed.de","agreement":"Mit dem Speichern dieser Seite versicherst du, dass du deinen Beitrag (damit sind auch Änderungen gemeint) selbst verfasst hast bzw. dass er keine fremden Rechte verletzt. Du willigst ein, deinen Beitrag unter der <a href=\"https://creativecommons.org/licenses/by-sa/4.0/deed.de\">Creative Commons Attribution/Share-Alike Lizenz 4.0</a> (https://creativecommons.org/licenses/by-sa/4.0/deed.de) und/oder unter einer gleichwertigen Lizenz zu veröffentlichen, welche der Serlo Education e. V. entsprechend der Regelungen in den <a href=\"/21654\">Nutzungsbedingungen</a> (http://de.serlo.org/21654) festlegen darf. Falls du den Beitrag nicht selbst verfasst hast, muss er unter den <a href=\"/21654\">Nutzungsbedingungen</a> (http://de.serlo.org/21654) verfügbar sein und du stimmst zu, notwendigen Lizenzanforderungen zu folgen.","iconHref":"https://i.creativecommons.org/l/by-sa/4.0/88x31.png"},"revision":0,"changes":"angelegt","content":"{\"plugin\":\"exercise\",\"state\":{\"content\":{\"plugin\":\"rows\",\"state\":[{\"plugin\":\"text\",\"state\":[{\"type\":\"p\",\"children\":[{\"text\":\"Gegeben ist folgendes Datenschema und Klassendiagramm:\"}]}]},{\"plugin\":\"image\",\"state\":{\"src\":\"https://assets.serlo.org/5e8cb7eb951cc_d43bb64b47189d1cfa911ceefa12bb00fbc292a1.png\",\"alt\":\"Klassendiagramm mit Schlüsseln zur Filmdatenbank\"}},{\"plugin\":\"image\",\"state\":{\"src\":\"https://assets.serlo.org/5e8cbbaecc42e_07af9cd3278005b66a52dd74343dfb6d9bc63993.png\",\"alt\":\"Datenschema mit Schlüsseln zur Filmdatenbank\"}},{\"plugin\":\"text\",\"state\":[{\"type\":\"p\",\"children\":[{\"text\":\"Ergänze für alle drei Relationen alle Datentypen.\"}]}]}]}}}","text-solution":{"id":0,"license":{"id":0,"title":"","url":"","agreement":"","iconHref":""},"revision":0,"changes":"","content":"{\"plugin\":\"solution\",\"state\":{\"prerequisite\":{\"id\":\"160143\",\"title\":\"Datentypen in DBMS\"},\"strategy\":{\"plugin\":\"text\",\"state\":[{\"type\":\"p\",\"children\":[{\"text\":\"Überlege dir \"},{\"type\":\"a\",\"href\":\"/65237\",\"children\":[{\"text\":\"Attributwerte\"}]},{\"text\":\" zu den \"},{\"type\":\"a\",\"href\":\"/65234\",\"children\":[{\"text\":\"Attributen\"}]},{\"text\":\" und entscheide dann, ob es ein Text, eine Zahl oder ein Datum/eine Uhrzeit ist.\"}]}]},\"steps\":{\"plugin\":\"rows\",\"state\":[{\"plugin\":\"text\",\"state\":[{\"type\":\"p\",\"children\":[{\"text\":\"Wegen der Referenzen wird zuerst die Relation PERSON angeschaut.\"}]}]},{\"plugin\":\"text\",\"state\":[{\"type\":\"h\",\"level\":3,\"children\":[{\"text\":\"Attribute der Relation PERSON\"}]}]},{\"plugin\":\"text\",\"state\":[{\"type\":\"unordered-list\",\"children\":[{\"type\":\"list-item\",\"children\":[{\"type\":\"list-item-child\",\"children\":[{\"text\":\"Nickname: Auch wenn es ein Schlüssel ist, ist es ein Wort. Hier kann man bei der maximalen Länge Knausern. Kein Auffüllen erwünscht. -> VARCHAR(15)\"}]}]},{\"type\":\"list-item\",\"children\":[{\"type\":\"list-item-child\",\"children\":[{\"text\":\"Name: Ein Text. Die Maximallänge kann zum Beispiel 20 sein. Kein Auffüllen erwünscht. -> VARCHAR(20)\"}]}]},{\"type\":\"list-item\",\"children\":[{\"type\":\"list-item-child\",\"children\":[{\"text\":\"Lieblingsgenre: Analog zu Genre. -> VARCHAR(20)\"}]}]}]}]},{\"plugin\":\"separator\"},{\"plugin\":\"text\",\"state\":[{\"type\":\"h\",\"level\":3,\"children\":[{\"text\":\"Attribute der Relation FILM\"}]}]},{\"plugin\":\"text\",\"state\":[{\"type\":\"unordered-list\",\"children\":[{\"type\":\"list-item\",\"children\":[{\"type\":\"list-item-child\",\"children\":[{\"text\":\"FilmID: Der \"},{\"type\":\"a\",\"href\":\"/69734\",\"children\":[{\"text\":\"künstliche Schlüssel\"}]},{\"text\":\" ist am besten eine Zahl. Diese lässt sich von der Datenbank automatisch hochzählen. -> INT\"}]}]},{\"type\":\"list-item\",\"children\":[{\"type\":\"list-item-child\",\"children\":[{\"text\":\"Titel: Der Titel ist ein Text. Man kann die maximale Zeichenzahl zum Beispiel auf 30 setzen. Es sollte nicht mit Leerzeichen auffüllen. -> VARCHAR(30)\"}]}]},{\"type\":\"list-item\",\"children\":[{\"type\":\"list-item-child\",\"children\":[{\"text\":\"Genre: Das Genre ist ein Text. Hier reichen vermutlich 20 Zeichen und wieder sollte nicht aufgefüllt werden. -> VARCHAR(20)\"}]}]},{\"type\":\"list-item\",\"children\":[{\"type\":\"list-item-child\",\"children\":[{\"text\":\"Laenge: Am Einfachsten ist es, die Länge in Minuten zu speichern. Dann ist es eine Zahl. -> INT\"}]}]},{\"type\":\"list-item\",\"children\":[{\"type\":\"list-item-child\",\"children\":[{\"text\":\"Oscarnominierungen: Eine Zahl. -> INT\"}]}]},{\"type\":\"list-item\",\"children\":[{\"type\":\"list-item-child\",\"children\":[{\"text\":\"Oscars: Eine Zahl. -> INT\"}]}]},{\"type\":\"list-item\",\"children\":[{\"type\":\"list-item-child\",\"children\":[{\"text\":\"hat: Als \"},{\"type\":\"a\",\"href\":\"/69734\",\"children\":[{\"text\":\"Fremdschlüssel\"}]},{\"text\":\" muss es den gleichen Typ haben wie \"},{\"text\":\"Nickname. \",\"em\":true},{\"text\":\"-> VARCHAR(15)\"}]}]}]}]},{\"plugin\":\"separator\"},{\"plugin\":\"text\",\"state\":[{\"type\":\"h\",\"level\":3,\"children\":[{\"text\":\"Attribute der Relation schaut\"}]}]},{\"plugin\":\"text\",\"state\":[{\"type\":\"unordered-list\",\"children\":[{\"type\":\"list-item\",\"children\":[{\"type\":\"list-item-child\",\"children\":[{\"text\":\"FilmID: Als Fremdschlüssel muss es den gleichen Typ haben wie \"},{\"text\":\"FilmID\",\"em\":true},{\"text\":\". -> INT\"}]}]},{\"type\":\"list-item\",\"children\":[{\"type\":\"list-item-child\",\"children\":[{\"text\":\"Nickname: Als Fremdschlüssel muss es den gleichen Typ haben wie \"},{\"text\":\"Nickname\",\"em\":true},{\"text\":\". -> VARCHAR(15)\"}]}]}]}]},{\"plugin\":\"text\",\"state\":[{\"type\":\"h\",\"level\":3,\"children\":[{\"text\":\"Datenbankschema\"}]}]},{\"plugin\":\"text\",\"state\":[{\"type\":\"p\",\"children\":[{\"text\":\"Alles zusammen sieht so aus:\"}]}]},{\"plugin\":\"image\",\"state\":{\"src\":\"https://assets.serlo.org/5e8cc29a92ccf_07af9cd3278005b66a52dd74343dfb6d9bc63993.png\",\"alt\":\"Datenbankschema mit Datentypen\"}}]}}}"}}}}"``

**Comment by inyono** [comment]
Was a false-positive trigger of a Cloudflare Firewall Rule
