### ISSUE TITLE
Course pages on further edited course are added twice

### ISSUE THREAD

**Issue by metzgaria** [serlo/serlo.org#353]
In https://de.serlo.org/160558 are many pages duplicated.
I added almost the whole course at once but then saved and edited some pages further.
The duplicates appeared after the reviewing process and have not been there yesterday.

**Comment by metzgaria** [comment]
I need to delete the duplicates so that the course can be used.
You can see the duplicates in revision 160998 of the whole course

**Comment by CarolinJaser** [comment]
In Backlog (https://docs.google.com/document/d/1rSkFo2JtsSwHHsbosQcgAN4EzeePXLnqi_eCFpUM3u4/edit#) verschoben
