### ISSUE TITLE
Diashow-plugin

### ISSUE THREAD

**Issue by jakobwes** [serlo/serlo.org#354]
To visualize certain things in an article for example a diashow-plugin would be amazing. There is a workaround using GeoGebra at the moment (see here https://docs.google.com/document/d/1Z9RUTkmXp5m8Eu4FjwYjUyuxkZTJDcTA3w_JLpQLJ7M/edit#heading=h.j1m9f32bsb3l) but this could also be natively developed.
Could be useful in most subjects (not with automatic image-switch, but by clicking/typing further)

**Comment by CarolinJaser** [comment]
Incldude in Google Doc https://docs.google.com/document/d/1rSkFo2JtsSwHHsbosQcgAN4EzeePXLnqi_eCFpUM3u4/edit#
