### ISSUE TITLE
Ordering Elements on a line - exercise-plugin

### ISSUE THREAD

**Issue by jakobwes** [serlo/serlo.org#355]
There are certain usecases where it is important to order elements on a line. For example in math, when pupils are supposed to order numbers,... by size, in physics when pupils should convert between different units or in history when pupils shall order historical events chronologically. For this an exercise-plugin would be amazing!

**Comment by Entkenntnis** [comment]
Ordering elements can be done in several different ways, and I have seen  many different solutions on https://anton.app, here are some examples:

![grafik](https://user-images.githubusercontent.com/13507950/78908518-7d9d0100-7a82-11ea-94fb-27aa7f57f55d.png)

![grafik](https://user-images.githubusercontent.com/13507950/78908623-a6bd9180-7a82-11ea-865c-8ad43d525370.png)

![grafik](https://user-images.githubusercontent.com/13507950/78908710-c48af680-7a82-11ea-8682-e34bcf289f57.png)

Another variant is http://learningapps.org with "Einfache Reihenfolge":

![grafik](https://user-images.githubusercontent.com/13507950/78909133-598def80-7a83-11ea-8b94-1717b1daee5b.png)

And another open source variant: https://felix-riesterer.de/main/seiten/quizze.html, implemented on ZUM-Wiki.

![grafik](https://user-images.githubusercontent.com/13507950/78909279-91953280-7a83-11ea-9163-dcdc7ddd1f5b.png)

So yeah, there are tons of options out there, some of them open source, some are usable already, ...

**Comment by CarolinJaser** [comment]
Included in Google Doc https://docs.google.com/document/d/1rSkFo2JtsSwHHsbosQcgAN4EzeePXLnqi_eCFpUM3u4/edit#
