### ISSUE TITLE
edtr-io: improve link creation UX

### ISSUE THREAD

**Issue by yolo-bird** [serlo/serlo.org#358]
If you link Serlo Content using the Serlo-ID and you omit the "/" before the ID, then the link will lead you directly into editing that specific content (i.e. you will be directly in the editor).

**Comment by inyono** [comment]
Known and working as intended (link URLs are handled the same as `href`, so it needs to be absolute for ids)

**Comment by yolo-bird** [comment]
Ok, thanks.

**Comment by inyono** [comment]
Btw: this is the same behavior as in the old editor. We could discuss UI improvements in the future (e.g. you choose whether you want to link an external site (`https://google.com`), link to an entity (`123`, maybe even with an automated search), or link to an anchor (`#foo-bar`, with auto-complete))

**Comment by yolo-bird** [comment]
Not relevant any longer
