### ISSUE TITLE
edtr-io: MathQuill auto-parenthesis bug

### ISSUE THREAD

**Issue by yolo-bird** [serlo/serlo.org#359]
Tried to edit this content: serlo.org/138662
The editor automatically adds the first opening parenthesis (on the left side of the equation), when adding the last closing parenthesis (on the right side of the equation)
![Screenshot_2020-04-08 Serlo – Die freie Lernplattform](https://user-images.githubusercontent.com/46370375/78915095-b392b300-7a8b-11ea-8b2e-f7d4920a5d01.png)

**Comment by inyono** [comment]
Okay, this is some weird behaviour with MathQuill. It works when you also delete the open parenthesis before `B` before trying to insert the closing one -.-. Not sure if we can do much here

**Comment by inyono** [comment]
see https://de.serlo.org/entity/repository/compare/138665/160855
