### ISSUE TITLE
editor removes inline code when editing content again

### ISSUE THREAD

**Issue by metzgaria** [serlo/serlo.org#365]
I can add inline code ~and it is correctly displayed after saving~(it had once...).
But when I want to further edit the content, the Inline-Code is removed.
You can try it out here: https://de.serlo.org/69747 (article)
And it also happened (and i didn't see it and saved it) here: https://de.serlo.org/161018 (course)

**Comment by kulla** [comment]
How where you able to add inline code? I have not found such a possibility in the format menu for text...

**Comment by kulla** [comment]
Answer: "Ist ein slate plugin
Wird aktuell im Editor über strg+q aktiviert, aber nach dem Speichern nicht mehr angezeigt -zum alten oder neuen Design weiß ich nichts."

**Comment by inyono** [comment]
Seems like this is a Slate-internal shortcut that we don't support explicitly at the moment. If needed, we could inline code as a configurable feature to the text plugin (so that we can activate it in informatics but disable it in other subjects).

**Comment by kulla** [comment]
Moved to Google document with feature requests
