### ISSUE TITLE
SC/MC-Preview in editmode is not working correctly

### ISSUE THREAD

**Issue by metzgaria** [serlo/serlo.org#369]
When adding a Single Choice/Multiple Choice Exercise, the preview is completely empty, even after adding answer options.
Only if you click "Aktivieren" after you added buttons, you can see them in the preview (also when the plugin is not focsued).

**Comment by kulla** [comment]
What is the behavior you wish / expect? Do you want to have SC/MC in WYSIWYG mode?

**Comment by CarolinJaser** [comment]
Moved to Google Doc https://docs.google.com/document/d/1rSkFo2JtsSwHHsbosQcgAN4EzeePXLnqi_eCFpUM3u4/edit#
