### ISSUE TITLE
donation-profiles: causes collapsibles to fail

### ISSUE THREAD

**Issue by inyono** [serlo/serlo.org#374]
Can't expand collapsibles (like solutions) anymore. Probably because of modifying DOM (anchors to be more precise) w/o letting Bootstrap know.

**Comment by kulla** [comment]
It seems to an issue with upgrading jQuery to `3.5.0`: https://github.com/twbs/bootstrap/issues/30553

**Comment by kulla** [comment]
Yes, that's the issue. Setting jQuery to `3.4.1` fixes the issue... :-)
