### ISSUE TITLE
Update jQuery to 3.5.0

### ISSUE THREAD

**Issue by kulla** [serlo/serlo.org#378]
Follow up of #374: Currently we cannot update jQuery to `3.5.0` since afterwards collapsible wouldn't work any more (see issue https://github.com/twbs/bootstrap/issues/30553 ). We need to wait until https://github.com/twbs/bootstrap/pull/30559 got deployed in a new version (which should be bootstrap `4.4.2`).

**Comment by inyono** [comment]
When we have a fix, remove the `resolution` for both `jquery` and `react-mathquill` (which depends on `jquery`)

**Comment by inyono** [comment]
Resolved in jQuery 3.5.1
