### ISSUE TITLE
Kommunikation zur Eingabe der E-Mail-Adresse

### ISSUE THREAD

**Issue by simonkoehl** [serlo/serlo.org#380]
Wir könnten den Satz "Bitte E-Mail-Adresse eingeben" ändern durch "An welche E-Mail-Adresse dürfen wir dir eine einmalige Bestätigung schicken?"

- [ ] ggf. auch im /spenden Formular umsetzen

**Comment by kulla** [comment]
Ist leider nicht möglich. Ich habe eine Support-Anfrage geschickt...

**Comment by kulla** [comment]
Antowrt von Twingle: "der Text lässt sich leider nicht so ohne weiteres für einzelne Kunden oder Projekte ändern. Wir haben jetzt allerdings den Standard-Text etwas abgeändert in "Bitte E-Mail-Adresse für die Bestätigung eingeben". Ich hoffe das ist in Ihrem Sinne."
