### ISSUE TITLE
Query where ID's are linked and embedded

### ISSUE THREAD

**Issue by yolo-bird** [serlo/serlo.org#385]
→ Abfrage für alle Autor*innen: Kann ID eintragen und finde alle Lerninhalte, die eine Verlinkung auf Inhalt enthalten bzw den Lerninhalt eingebunden haben
→ zusätzlich Option unter den Einstellungen, verknüpfte Elemente anzuzeigen → Weiterleitung auf Abfrage mit bereits eingetragener ID
Falls technische nicht viel komplexer: Erweiterung der Funktionalität auf Anker:
-> Bei Eingabe der ID finde ich auch alle Links auf Anker auf der entsprechenden Seite. 
→ Statt einer ID kann ich auch ID+Anker eingeben und bekommen nur Seiten, die direkt auf diesen Anker verlinken.

**Comment by inyono** [comment]
Did you already prioritize this compared to the other stuff we currently have from the authors units?

**Comment by inyono** [comment]
> → zusätzlich Option unter den Einstellungen, verknüpfte Elemente anzuzeigen → Weiterleitung auf Abfrage mit bereits eingetragener ID
I don't understand this point

**Comment by yolo-bird** [comment]
Does not alter the prioritization as we discussed yesterday. Maybe when we arrive at converting articles the priority will rise...


One of the Options in this menu. Or did you mean the forwarding part?
![Screenshot_2020-04-20 Mathematik](https://user-images.githubusercontent.com/46370375/79776082-7b199180-8335-11ea-9938-8b4332c24cf8.png)

**Comment by inyono** [comment]
Nah, that makes sense. Thanks.

**Comment by CarolinJaser** [comment]
Moved to Google Doc https://docs.google.com/document/d/1rSkFo2JtsSwHHsbosQcgAN4EzeePXLnqi_eCFpUM3u4/edit#
