### ISSUE TITLE
edtr.io: anchor jumps below headings

### ISSUE THREAD

**Issue by yolo-bird** [serlo/serlo.org#389]
If I click on an anchor, e.g "wie du auf serlo.org Bilder einbinden kannst", I directly land below the heading. This leaves me confused as I do not have immediate orientiaton. I would love to have the heading included. Hope this is understandable :-)

![Screenshot_2020-04-23 Bilder und Grafiken](https://user-images.githubusercontent.com/46370375/80072870-22b9de00-8547-11ea-8e28-dfc51b657076.png)
and here I do land
![Screenshot_2020-04-23 Bilder und Grafiken(1)](https://user-images.githubusercontent.com/46370375/80072897-2a798280-8547-11ea-827b-c034a9c6ab0f.png)

**Comment by Knorrke** [comment]
This fixed it for the old content: https://github.com/serlo/serlo.org/blob/46266e20b00e9cd0d66d7e2cbe15e2625f2c3ceb/packages/public/client/src/frontend/styles/_shame.scss#L90-L112
Probably just need to change the selectors to match anchors by the new editor.

**Comment by yolo-bird** [comment]
fixed in the new frontend
