### ISSUE TITLE
edtr.io: Editing formulas in latex mode covers preview

### ISSUE THREAD

**Issue by yolo-bird** [serlo/serlo.org#390]
See: https://de.serlo.org/entity/repository/add-revision/137561

![Screenshot_2020-04-23 Serlo – Die freie Lernplattform](https://user-images.githubusercontent.com/46370375/80081392-2ce1d980-8553-11ea-9860-9a93cf35b4ef.png)

Funnily enough when opening the screenshot tool the editing box jumps so that at least a part of the preview becomes visible. But before that the edition box really covered the preview completely.

**Comment by CarolinJaser** [comment]
Moved to Google Doc https://docs.google.com/document/d/1rSkFo2JtsSwHHsbosQcgAN4EzeePXLnqi_eCFpUM3u4/edit#
