### ISSUE TITLE
bug: formulas vanish completely when converting certain entities

### ISSUE THREAD

**Issue by yolo-bird** [serlo/serlo.org#392]
Try to convert https://de.serlo.org/147589.

Weirdly enough this happens most often in https://de.serlo.org/mathe-pruefungen, though not for every exercise and not exclusively in this area. 

Priority is quite high as manually copiing formulas takes a lot of time.

**Comment by inyono** [comment]
Can you link to the revision that was problematic? In the history, the "k" revision seems fine.

**Comment by yolo-bird** [comment]
For the solution the "k" revision is problematic: https://de.serlo.org/entity/repository/compare/148511/158664

**Comment by kulla** [comment]
I have found the bug: Currently equations of the form `$$ ... $$` in markdown are effected which are written inline (which do not have their own line in the markdown code). For example the following formula would not convert correctly:

```Theorem of pythagoras: $$a^2+b^2=c^2$$```

In contrast the following code would convert correctly:

```
Theorem of pythagoras:

$$a^2+b^2=c^2$$
```
