### ISSUE TITLE
i18n of editor

### ISSUE THREAD

**Issue by jakobwes** [serlo/serlo.org#395]
All strings of the editor should be contained in Crowdin and translatable via that. That would be really important for winning and integrating new editors in the language-versions who do not speak german.

**Comment by inyono** [comment]
WIP, ping #302 #315

**Comment by jakobwes** [comment]
Ahh, amazing! Thanks for the info.

**Comment by inyono** [comment]
Closed via #353, going to be released with additional improvements after #413 is done.
