### ISSUE TITLE
show status to new authors & reviewers

### ISSUE THREAD

**Issue by simonkoehl** [serlo/serlo.org#399]
Dependency: #400 

Show new authors and reviewers, that they are on their way to become official active authors and reviewers

Suggestion
- show bird but "ausgegraut"
- show text "Du hast X Bearbeitungen/Reviews in den letzten 90 Tagen vorgenommen. Noch 10-X Bearbeitungen/Reviews und du erhältst den offiziellen Status als Autorin bzw. Autor/Reviewerin bzw. Reviewer unserer Community. Falls du Aufgaben oder Hilfe suchts, schreib uns einfach im [Community Chat]. Viel Spaß :)"

**Comment by kulla** [comment]
Moved to project overview document of P Community Upgrade
