### ISSUE TITLE
Not possible to add answers to sc-mc-exercises

### ISSUE THREAD

**Issue by inyono** [serlo/serlo.org#40]
E.g. https://de.serlo.org/entity/repository/add-revision/142439

> TypeError: "e.button is undefined"

**Comment by inyono** [comment]
Also see https://sentry.io/organizations/serlo/issues/1197328713/?project=1518830&query=is%3Aunresolved+edtr-io%3Atrue

**Comment by Knorrke** [comment]
fixed in https://github.com/edtr-io/edtr-io/pull/193
