### ISSUE TITLE
present & appreciate individual community members on learning plattform

### ISSUE THREAD

**Issue by simonkoehl** [serlo/serlo.org#401]
Possible set up
- select random active author or reviewer, who contributed to a learning content and who filled out her/his profile (dependency: #402)
- present as: "Heute sagen wir danke an unsere Autorin bzw. unseren Autor _username_!"
- show profile picture/avatar and "Warum mache ich bei Serlo mit"-Text

OR show donor (e.g. 50/50 with author/reviewer)
- select random donor (no connection to content on page) who filled out her/his profile
- present as "Serlo ist und bleibt komplett kostenlos und werbefrei dank _username_"
- show profile picture/avatar and "Warum spende ich an Serlo"-Text

Possible follow ups
- combine with call to actions (like on profile pages)
- ask "prominent" donors to fill out their profile (e.g. Harald Lesch, Wieland Holfelder)
- acquire new donors with charisma and ask them to fill out their profile

**Comment by kulla** [comment]
Is already in the overview document for P Community Upgrade
