### ISSUE TITLE
Plan: standardize user profile

### ISSUE THREAD

**Issue by simonkoehl** [serlo/serlo.org#402]
optional content
- profile picture
- 2-3 standardized questions
- free field

adapt questions to profile roles
- for authors/reviewers: "Warum helfe ich bei Serlo mit"
- for donors: "Warum spende ich an Serlo"

to be discussed
- links to social media
- ?

combine with #372

**Comment by kulla** [comment]
Planning so far done. Issue for tracking the implementation: https://github.com/serlo/frontend/issues/935
