### ISSUE TITLE
improve profile stats

### ISSUE THREAD

**Issue by simonkoehl** [serlo/serlo.org#406]
General thought: Quantity of edits or comments might be a counterproductive KPI as quality is much more important

Do we have ideas to improve the stats in profiles regrading
- data?
- visualization?

*Data*
Do we have possibilitites to include and focus on impact related data like
- usage of content
- feedback from users
- feedback from reviewers
- upvotes/thumbsup for comments and replys

**Comment by kulla** [comment]
Planning done. Implementation will be tracked in https://github.com/serlo/serlo.org/issues/406
