### ISSUE TITLE
No notifications from RocketChat

### ISSUE THREAD

**Issue by yolo-bird** [serlo/serlo.org#409]
- no notifications via app or mail
- independent of mail provider

**Comment by inyono** [comment]
In General, the E-Mail sending & push notifications settings are correct. So might need to check the (default?) notification settings of rooms etc.

**Comment by yolo-bird** [comment]
-Weird, because there are also no notifications for private messages. Is this something RocketChat admins can/should check?

**Comment by inyono** [comment]
Possibly (don't know the Rocket.Chat Admin panel too well). Either some problem with our notification configuration or some bug in Rocket.Chat (didn't see one in the Rocket.Chat repo though)

**Comment by kulla** [comment]
Notifications seems to work again. I got notifications by email and app today for a message where I was pinged and also in sparkpost I see notification emails send again. Thus I close this issue.

@yolo-bird Reopen it, if it is necessary or write us in #meta-dev
