### ISSUE TITLE
Design of Mailings from notifications@mail.serlo.org and text changes

### ISSUE THREAD

**Issue by kathongi** [serlo/serlo.org#412]
Wolfgang und ich haben gerade die **erste Mail nach der Registrierung von Autor*innen** verändert.
Haben hier festgehalten, wie es in der deutschen und englischen Fassung aussehen sollte: https://docs.google.com/document/d/1Nukg5Ivy3ZmjUC2froKoZUvHf3SbD3IxzavGnatNoXw/edit?usp=sharing

In CrowdIn hab ich noch die deutsche Version für die Mail geschrieben: https://crowdin.com/translate/serlo/2/en-de#q=mail
Bitte nochmal drüber schauen.

Im Google Doc ist auch ein Design Vorschlag für die Mail. Wär gut, wenn **alle Mails von notifications@mail.serlo.org** gleich aussehen. Daher hab ich die Mails, die wir von Rocket Chat bekommen, in der Untersuchungsumgebung abgeändert (siehe Doc). Design kann aus diesen Mailings entnommen werden. Für die Signatur hab ich den html Code ins Doc reinkopiert.
Das Design solll für alle Mails von notifications@mail.serlo.org eingestellt werden. Also insb die Mails zu den "ungelesenen Benachrichtigungen auf Serlo".

**Comment by kulla** [comment]
@kathongi Do you want to include a "Do not reply" (see #388) in those mails?

**Comment by kathongi** [comment]
> @kathongi Do you want to include a "Do not reply" (see #388) in those mails?

Yes please

**Comment by kulla** [comment]
Moved to google doc with feature requests so that this issue can be prioritized there together with other issues.
