### ISSUE TITLE
Do not allow empty content to be saved

### ISSUE THREAD

**Issue by yolo-bird** [serlo/serlo.org#420]
Right now courses and articles can be saved, if there is only a title but no course page resp. no text in the article. This should not be possible as finding empty content is not a great user experience for students.

**Comment by kulla** [comment]
@yolo-bird I have added this issue in https://github.com/orgs/serlo/projects/17#card-38211155 where you can prioritize it.

**Comment by CarolinJaser** [comment]
Moved to Google Doc https://docs.google.com/document/d/1rSkFo2JtsSwHHsbosQcgAN4EzeePXLnqi_eCFpUM3u4/edit#
