### ISSUE TITLE
prevent learning content AND sub-topics under one taxonomy page

### ISSUE THREAD

**Issue by simonkoehl** [serlo/serlo.org#422]
e.g. https://de.serlo.org/mathe/funktionen/ableitung-funktionen

May be we have to prevent this by design ..

**Comment by yolo-bird** [comment]
Moced to https://docs.google.com/document/d/1rSkFo2JtsSwHHsbosQcgAN4EzeePXLnqi_eCFpUM3u4/edit#heading=h.4tcy6e392675
