### ISSUE TITLE
Function to copy entities (inside and between instances)

### ISSUE THREAD

**Issue by jakobwes** [serlo/serlo.org#427]
Such a function would make it way easier to create and translate big amounts of content based on the work already done in the german language-version (and would increase the connections between the language-versions). One could copy an article e.g. to the spanish-language-version and the authors could use the german article as a skeleton which only needs to be adapted, thus making content work far easier.

**Comment by CarolinJaser** [comment]
Moved to Google Doc https://docs.google.com/document/d/1rSkFo2JtsSwHHsbosQcgAN4EzeePXLnqi_eCFpUM3u4/edit#
