### ISSUE TITLE
i18n: use correct legal pages

### ISSUE THREAD

**Issue by inyono** [serlo/serlo.org#429]
i18n still uses the old legal pages (e.g. see /user/register). Check that terms / privacy / imprint are correct everywhere.

We should also redirect from the old versions to the new versions.

**Comment by jakobwes** [comment]
Also maybe in addition: if you search for "http" you can find three pages which also in the englisch version link on the german /community. This could be changed together with the other modifications in crowdin.

**Comment by yolo-bird** [comment]
I see the following steps: 
- update the english version
- translate the corresponding pages via crowdin
- archive the old pages /impressum, /datenschutzerklaerung & /nutzungsbedingungen

**Comment by CarolinJaser** [comment]
This is not relevant any longer since we have redirections that deal with this issue
