### ISSUE TITLE
Initialize Google analytics in other language-versions to track user numbers

### ISSUE THREAD

**Issue by jakobwes** [serlo/serlo.org#432]
It is already implemented on ta.serlo.org and en.serlo.org and would be amazing if this would also be possible on the other language versions

**Comment by inyono** [comment]
Tracking code is already included, one does only need to create the appropriate views / filters in Google Analytics.

**Comment by kulla** [comment]
I have added all views / filter to google analytics. Note that currently the views are empty since they only start from now with collecting the data.
