### ISSUE TITLE
Quick fixes sign up

### ISSUE THREAD

**Issue by metzgaria** [serlo/serlo.org#433]
- [ ] redirection to the page you visited before the registration process after completing the registration
- [ ] you are already logged in after following the registration confirmation link in the email
- [ ] If you singed up and go to sing in it says something like "Your account hasn't been approved yet". Here we should point to the confirmation email.
- [ ] improve role descriptions (see comment below)

**Comment by simonkoehl** [comment]
- [ ] improve role descriptions 

Ich bin hier...
- um zu lernen (Zusammenführung von SchülerIn und StudentIn; inkludiert auch Auszubildende, etc.)
- als Lehrer:in
- als Elternteil

-> multiple choice und nicht single choice

**Comment by kulla** [comment]
Moved to the new google doc with feature requests (see https://serlo.slack.com/archives/C0BM3MHK4/p1620129431000600 )

**Comment by simonkoehl** [comment]
@CarolinJaser Kann es sein, dass ihr übersehen hattet, meinen Kommentar "improve role descriptions" ebenfalls als feature request in das Google Doc aufzunehmen? Hab das dort zumindest auf die Schnelle nicht wiedergefunden..

**Comment by CarolinJaser** [comment]
@simonkoehl stimmt, das haben wir nicht mit eingetragen. Habe das nachgeholt und ist jetzt beim Verbessern des Registrierungsprozesses mit drin

**Comment by simonkoehl** [comment]
@CarolinJaser danke!!
