### ISSUE TITLE
Replace subject start pages with taxonomy subject level

### ISSUE THREAD

**Issue by simonkoehl** [serlo/serlo.org#444]
Der Vorschlag ist, als Startseite für ein Fach auf Serlo künftig direkt die Taxonomy zu nehmen, sprich für Mathematik: https://de.serlo.org/mathe/5

Dort packen wir oben in die Description die allerwichtigsten Informationen und verlinken auf eine About-Seite, wo quasi die aktuelle Startseite hinkommt (natürlich ohne die manuell gebaute “Navigation”)

Begründung:
- Die Navigation auf der static page nachzubauen ist keine skalierbare Lösung
- Die Nutzer kommen schneller zum Inhalt und sehen direkt den kompletten Umfang unseres Angebots
- Das würde das Anlegen eines neuen Fachs vereinfachen, weil wir nicht erst eine static page brauchen.

Sub-Issue suggestion
- [ ] rename "Mathe" to "Mathematik"

**Comment by kulla** [comment]
Duplicate issue: https://github.com/serlo/serlo.org/issues/266

**Comment by yolo-bird** [comment]
Moved to https://docs.google.com/document/d/1rSkFo2JtsSwHHsbosQcgAN4EzeePXLnqi_eCFpUM3u4/edit#
