### ISSUE TITLE
Don't index course pages individually

### ISSUE THREAD

**Issue by inyono** [serlo/serlo.org#445]
Considering serlo/athene2#686 and the issues when searching for courses, we should have a view for the course itself that contains the content for all pages. Links to individual course pages should instead go to the root course (w/ JavaScript only showing the relevant page; see also https://support.google.com/webmasters/answer/66353?hl=en). This should solve all the issues (indexing courses, duplicated content). The only thing we lose with this (and let's discuss if that's a problem and if we could get around that), is that you can't get directly to an individual course page from the search (you would instead get to the beginning of the course). IMHO: this is fine since you'd usually won't start in the middle of the course, anyways.

**Comment by kulla** [comment]
Moved idea to new google document for feature requests
