### ISSUE TITLE
Part of the text missing starting page of es.serlo.org

### ISSUE THREAD

**Issue by jakobwes** [serlo/serlo.org#446]
In es.serlo.org in the graphic:

![CopyPasteDesign 2020-06-15 at 19 58 52](https://user-images.githubusercontent.com/13718882/85139435-b4428500-b244-11ea-8e5c-49abf802ab81.png)

a part of the text is missing.

**Comment by inyono** [comment]
Any SVG wizards here that could look into that? 😅
