### ISSUE TITLE
Converting lists does not work correctly

### ISSUE THREAD

**Issue by Knorrke** [serlo/serlo.org#452]
Before converting the list looks like this:
![grafik](https://user-images.githubusercontent.com/11499926/85871322-8625ed80-b7ce-11ea-8a6a-c628bd62f980.png)

When converting, it looks like in the gif below. As you can see, there's a blank line that can't be focused and the list editing behaves wrong (backspace and toolbar).
![liste](https://user-images.githubusercontent.com/11499926/85871543-d604b480-b7ce-11ea-8f9d-f7d627adc76e.gif)

**Comment by Knorrke** [comment]
Checking with the document inspector, there is some additional slate `"block"` element inside the `<li>` (highlighted).
![grafik](https://user-images.githubusercontent.com/11499926/85872071-8f638a00-b7cf-11ea-9dab-750d3baea738.png)

**Comment by inyono** [comment]
Thanks for the issue. Can you give me the link to the revision that contains the first example?

**Comment by Knorrke** [comment]
sure, sorry. This is the article: https://de.serlo.org/48121 and specifically this is the current revision I'm trying to edit https://de.serlo.org/67331

also the informatik landing page has a saved revision with broken list structure: https://de.serlo.org/informatik

**Comment by yolo-bird** [comment]
It is quite a pain to fix this manually. Let's discuss this issue tomorrow.

**Comment by yolo-bird** [comment]
I just noticed that in the redesign the broken lists look fine. You can check it for https://de.serlo.org/informatik.

**Comment by kulla** [comment]
Moved to document with feature requests
