### ISSUE TITLE
SEO: XML-Sitemaps – collect URLs in XML-Sitemaps

### ISSUE THREAD

**Issue by MMitzko** [serlo/serlo.org#454]
This is a big task again ;). Please make sure that you’ve got enough capacities in the Team and that there are no other important priorities before starting.

Vroni (SEO consulting) said that collecting the URLs in XML-Sitemaps is very important for SEO. But once we collect them it’s imperative to update them regularly, so we should do this task just if we can make sure that we have enough capacities.

**Comment by yolo-bird** [comment]
Moved to the backlog document
