### ISSUE TITLE
Creating content does not on serlo.org

### ISSUE THREAD

**Issue by jakobwes** [serlo/serlo.org#459]
Across most (all) language-versions (including de.serlo.org) when trying to create an article (don't know if it affects other content-types) one gets redirected onto a blank page with the url in the form: `https://es.serlo.org/entity/create/article?taxonomy%5Bterm%5D=171469` from where no action is possible.

**Comment by inyono** [comment]
Fixed in https://github.com/serlo/serlo.org/commit/8ddb5a623a1148d33817f1c2f879c414916a55f6
