### ISSUE TITLE
Dev & staging serlo.org (legacy) uses production js and css

### ISSUE THREAD

**Issue by kulla** [serlo/serlo.org#481]
The website https://de.serlo-development.dev/ uses https://packages.serlo.org/ for JS and CSS instead of https://packages.serlo-development.dev/ Thus we cannot test changes in the client package in dev or staging before it goes into production.

**Comment by kulla** [comment]
Okay, I see now that the difference is in the version number next to the client. So currently stagging and dev have the version number `14` ( https://packages.serlo.org/serlo-org-client@14/main.js ) while production is in `13.1.2` ( https://packages.serlo.org/serlo-org-client@13.1.2/main.js )

**Comment by inyono** [comment]
Yep, that's the intended usage: you can configure which stylesheets / scripts to use via server config. And usually, we just deploy a breaking change when necessary (like in this case were we depend on the new api).
