### ISSUE TITLE
GeoGebra Toolbar in Applet on serlo.org doesn't appear

### ISSUE THREAD

**Issue by kathongi** [serlo/serlo.org#484]
Toolbar in applet https://www.geogebra.org/m/qwzj23qy doesn't appear in https://de.serlo.org/140933 (Wie erstelle ich Grafiken?>Spoiler: Probier dich aus) 

geogebra:
![image](https://user-images.githubusercontent.com/44167220/90892568-c9ab6b00-e3bd-11ea-8efc-52490a438260.png)

serlo.org:
![image](https://user-images.githubusercontent.com/44167220/90892495-b1d3e700-e3bd-11ea-9508-17507c35e0b2.png)

Missing toolbar:
![image](https://user-images.githubusercontent.com/44167220/90892598-d4fe9680-e3bd-11ea-81c5-fb3404514801.png)

**Comment by kulla** [comment]
Moved to new google document with feature requests.
