### ISSUE TITLE
error 504 

### ISSUE THREAD

**Issue by kathongi** [serlo/serlo.org#487]
error 504 by copying some articles from https://de.serlo.org/1327 to https://de.serlo.org/16093

Reload doesn't fix the problem.

![image](https://user-images.githubusercontent.com/44167220/91458139-78035480-e885-11ea-839e-0aada9142977.png)

**Comment by inyono** [comment]
Which / how many articles did you want to copy?

**Comment by kathongi** [comment]
I tried copying 5 articles. Copying 2 articles worked :D

**Comment by inyono** [comment]
Yeah, copying stuff is rather resource-intensive (especially, if you move many articles). We might be able to optimize that, but a short-term workaround is to copy less entities at once.
