### ISSUE TITLE
Notification error: Keine Ansicht für Benachrichtigung "license/object/set" gefunden

### ISSUE THREAD

**Issue by kathongi** [serlo/serlo.org#489]
Strange notifications

![image](https://user-images.githubusercontent.com/44167220/91549512-55c21300-e927-11ea-9da2-4a71cb147d8f.png)

Propably because of license changes.

Notifications appeared for my serlo account kathongi (28.08.20)
Profil - aktuelle Aktivitäten
![image](https://user-images.githubusercontent.com/44167220/91550250-91111180-e928-11ea-92c1-78c8ee719900.png)

**Comment by kulla** [comment]
Should be fixed in the new design and I guess it is not necessary to fix this in the old design. @kathongi Reopen this issue, when you think this is still relevant.
