### ISSUE TITLE
Delete Spam-profiles

### ISSUE THREAD

**Issue by jakobwes** [serlo/serlo.org#490]
See here for a list: https://serlo.slack.com/archives/C0BMSC431/p1598548800002200

**Comment by jakobwes** [comment]
In addition to the slack-list here is another one quickly compiled: 
https://docs.google.com/document/d/1D7ulx33vPzsAN_mnm9yqQ5KmvXv7HiKil3H7EcJlib8/edit?usp=sharing 

(SimpleAnalytics for the english-version provides a good source)

**Comment by inyono** [comment]
Done. Might take a while until they are no longer cached.
