### ISSUE TITLE
Fix SMTP configuration at twingle

### ISSUE THREAD

**Issue by kulla** [serlo/serlo.org#506]
Ping @yolo-bird

**Comment by inyono** [comment]
What's this about? Does Twingle need (our) SMPT config? If so, I have the credentials for that.

**Comment by kulla** [comment]
This issue is a reminder for me: They have written me, that the SMTP config which we have stored there does not work and so we do not get an email when the donation form is used...

**Comment by kulla** [comment]
Fixed
