### ISSUE TITLE
api: implement smart cache for new endpoints

### ISSUE THREAD

**Issue by inyono** [serlo/serlo.org#514]
- [ ] subscriptions:
  - [ ] should be set when the user changes their subscriptions.
  - [ ] should be set for new users.
- [x] revisionIds:
  - [x] should be set when a revision is created or deleted.
  - [x] should be set when a new repository is created.
- [x] restore from bin
- [x] /user/profile/:username: should be set for new users.
- [ ] events: similarly, depending on actual implementation.
- [x] /api/threads/:id and /api/uuid/:commentid (wenn commentare hinzugefügt / aktualisiert werden)

**Comment by Entkenntnis** [comment]
https://github.com/serlo/frontend/issues/645 related.
