### ISSUE TITLE
Edtr-io: Deactivate duplicate-button

### ISSUE THREAD

**Issue by kulla** [serlo/serlo.org#520]
Quote from the chat: "Ich hab jetzt über eine Stunde an einer Aufgabe gesessen und habe anstatt ein Plugin zu löschen aus Versehen auf duplizieren geklickt. Jetzt kann ich nicht mehr speichern.
Könnt ihr Features, die so bombenmäßig viel zerstören können, ausgrauen, bis sie funktionieren?" 

@yolo-bird What do you think?

(ping @metzgaria for notification)

**Comment by inyono** [comment]
Duplicate functionality is working again in v1.3.1.
