### ISSUE TITLE
clarify author status

### ISSUE THREAD

**Issue by simonkoehl** [serlo/serlo.org#532]
- when does it start
- when does it end
- how can we appriciate very active authors in their inactive future
- to keep things simple, it the auhtor status on the plattform and from the team should be the same

e.g.
newbie (less than 10 edits)
-> active author (at least one edit within the last X days
-> inactive author (0 edits within the last X days)

**Comment by kulla** [comment]
Actually I have forgotten, why we have added this issue. With the current definition I do not see any reason to change this. When we add the `newbie` status to the frontend we may have a discussion about this any way. Thus I close this issue. @simonkoehl write me when you think this is still relevant.
