### ISSUE TITLE
idea: using events to measure user activity

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/serlo.org#535]
Most analytic tools (ga, sa, ...) allow us to define custom events and collect this data. Page views alone aren't a very accurate measure of how much a learner is actually interacting with the content. Maybe we can add some custom events to enrich our data, e.g.

- Open a solution
- Open a spoiler
- Submit an interactive exercise
- Share content

We are currently very reliant on data, as this is actually our only measure of success right now. So we would benefit if we can make the data more accurate.

**Comment by inyono** [comment]
Hm, why is this now in serlo.org? If you don't want to implement something for the frontend, I'd say we don't have a need for that yet.

**Comment by elbotho** [comment]
I see.
It seemed a bit meta.I have not looked into the SA Api yet so I wasn't even sure if we would implement it in the frontend or somewhere else.

**Comment by inyono** [comment]
If we implement it, it would definitely be in the frontend since it needs to be done on client-side (and specific to each project).

**Comment by yolo-bird** [comment]
Moved to https://github.com/serlo/serlo.org/issues/535
