### ISSUE TITLE
Course-menu not shown + no content on course-pages anymore

### ISSUE THREAD

**Issue by jakobwes** [serlo/serlo.org#537]
https://es.serlo.org/matem%C3%A1ticas/n%C3%BAmeros-y-medidas/operaciones-b%C3%A1sicas-de-aritm%C3%A9tica/operaciones-con-n%C3%BAmeros-enteros/operaciones-aritm%C3%A9ticas-con-n%C3%BAmeros-enteros/descripci%C3%B3n-general

Also today I added an empty space behind every title of a course-page to force a new-generation of the paths (so that all coursepages have a /matematicas-path and not some a /mathematicas-path and some a /community-path). Now no content is shown on the page, if not logged in (and if I'm in the new frontend and click on the link I just get forwarded to the old one without content). Just reverted these changes, but the error still persists

**Comment by kulla** [comment]
This seems to be an issue with the cache. When you are not logged in you get a cached content. It seems that it cannot find it properly after you have saved and you get thus an empty page until the cache gets invalidated. This will be fixed in the frontend though and thus do not recommend to fix it. Thx for reporting!

**Comment by jakobwes** [comment]
@kulla inyono wrote on slack that he wanted to look into it. Not sure if you have talked about it. Also issue still persists in new frontend, because I just get rerouted to the old one. May be a different bug, or related but would then maybe keep this bug open still.

**Comment by inyono** [comment]
I'll discuss that with @kulla and will reopen if necessary :)

**Comment by inyono** [comment]
Found the problem, there was a trailing space in the route in the backend, i.e. `taxonomy/term/get ` instead of `taxonomy/term/get`. Should be fixed as soon as the cache is invalidated.

**Comment by jakobwes** [comment]
Thank you for the fix @inyono. It works perfectly now!
