### ISSUE TITLE
Formulas in tables

### ISSUE THREAD

**Issue by kathongi** [serlo/serlo.org#541]
![image](https://user-images.githubusercontent.com/44167220/100097363-c7ddc180-2e5c-11eb-8d09-2ffd83e85f1c.png)
Formulas in tables aren't shown (in old design).

--> https://de.serlo.org/183740

**Comment by inyono** [comment]
Most likely: content created with the new editor and MathJax is not loaded (because I recently changed the logic to only load MathJax on legacy content). Problem: tables still rely on global MathJax.
