### ISSUE TITLE
stay within (curriculum) taxonomy

### ISSUE THREAD

**Issue by simonkoehl** [serlo/serlo.org#549]
entity view: stay within the taxonomy you came from (eg. curriculum) & enable linking to entity within an explizit taxonomy (eg. curriculum). This is relevant, when a entity is linked to different taxonomies.

possible solution: include parent folder ID as ?variable in URL

**Comment by inyono** [comment]
We might be able to do that in the redesign. This won't be feasible for the legacy system, though.

**Comment by simonkoehl** [comment]
I thought so. That's why I put it in the "strategy step 2" board backlog.

**Comment by yolo-bird** [comment]
Moved to https://docs.google.com/document/d/1rSkFo2JtsSwHHsbosQcgAN4EzeePXLnqi_eCFpUM3u4/edit#heading=h.n83ldkywxvv0
