### ISSUE TITLE
Redirects for "Schlau-Werkstatt"

### ISSUE THREAD

**Issue by yolo-bird** [serlo/serlo.org#550]
One of our content partners "Schlau-Werkstatt" would like to have 4 redirects to better promote the corresponding Serlo content. 

serlo.org/schlau-größen -> https://de.serlo.org/183604

serlo.org /schlau-geometrie -> https://de.serlo.org/183603

serlo.org /schlau-rechenregeln-rechenbegriffe -> https://de.serlo.org/146948

serlo.org /schlau-ganzezahlen -> https://de.serlo.org/183602

**Comment by inyono** [comment]
Hm... Can't they do that on their end? E.g. redirect something like `https://www.schlau-werkstatt.de/serlo-größen` to `https://de.serlo.org/183604`? This way, they are responsible for supporting those as long as they need the URLs.

**Comment by kulla** [comment]
@yolo-bird When they cannot do this redirect by their own you can help them setting up schlau-werkstatt.link (similar to serlo.link). Then they can manage the redirects by themselves.

**Comment by yolo-bird** [comment]
Thanx for the input. Then I'll further discuss the topic of redirects with them and will use one of the above mentioned solutions.
