### ISSUE TITLE
Add hashes to redirects after saving and accepting revisions (for frontend)

### ISSUE THREAD

**Issue by elbotho** [serlo/serlo.org#553]
For users who use the new frontend after a successful save should add a hash to the following redirect.

e.g. instead of 
`…/entity/repository/history/1681#revision-saved` redirect to `…/entity/repository/history/1681#revision-saved` 
or for admins or within the sandkasten: instead of `…/sinus-kosinus-und-tangens` redirect to `…/sinus-kosinus-und-tangens#revision-saved-accepted`

The same logic applies to accepting revisions:
here we could add a `#revision-accepted` to the url.

**Comment by kulla** [comment]
Why do you want to have the hash? In the long run there will be a mutation endpoint at api.serlo.org which can result in any object you need at the frontend.

**Comment by elbotho** [comment]
It's true, It would be an interim solution, but it could be a long while until we implement edtr.io in the frontend and have the mutations in place.
Please judge yourself if it's worth the effort (can't estimate that) and of course prioritise API work :)

**Comment by kulla** [comment]
Yeah, let's discuss this on Monday
