### ISSUE TITLE
Can't subscribe to content in staging

### ISSUE THREAD

**Issue by elbotho** [serlo/serlo.org#554]
low priority, works fine in production, unsubscribe also works immediately.

### steps
- login (preferably as a user with little subscriptions, but that's just comfort)
- visit any content that is not currently subscribed
- from the menu choose "subscribe" (with or without mail does not seem to matter)
- site seems to refresh, no notice is shown, no error is visible
- subscription is not added in `/subscriptions/manage` and the menu still offers the option to subscribe
- same 5 minutes later

**edit** 
This only occurs when I try to subscribe manually, when I edit content I get subscribed flawlessly and without  any delay.

**Comment by Entkenntnis** [comment]
I'm still seeing this issue. The API is not returning the new id.

**Comment by inyono** [comment]
Please create an new issue for that because this issue was for the legacy system and with a clear reproduction on what didn't work and this is fixed (was an issue with the new alias system).

**Comment by elbotho** [comment]
@inyono @Entkenntnis can confirm that it works as expected for me. 
(frontend interface needs a extra refresh atm.)
