### ISSUE TITLE
Navigation of a Spanish course not shown 

### ISSUE THREAD

**Issue by kulla** [serlo/serlo.org#559]
See https://es.serlo.org/community/recursos-para-educadores/serlo.org---tutorial-para-familiarizarse/chat-para-todas-las-preguntas 

In legacy version there is no navigation. However in the new design it is shown.

**Comment by inyono** [comment]
Wild guess: there's a trailing space in the navi backend somewhere -.-

**Comment by kulla** [comment]
@jakobwes Can you check this?

**Comment by jakobwes** [comment]
Just had a look at it. We didn't yet implement the topic-navigation for the community-subject in the backend (What in German and English you would have under "Community Overview"). Maybe it is related to that?

If so: is there on option of linking the taxonomy with the navigation, without having a label "Community Overview" always in the menu for everything under /community? I think this label doesn't really tell much to the users, which have no real reason to ever see the taxonomy-root of all content under /community (this page here: https://es.serlo.org/community/164234/community).

**Comment by inyono** [comment]
Well, the `Taxonomy\Provider\NavigationProvider` is essential for the navigation to work (as the name might suggest ^^). If you want a navigation (with e.g. breadcrumbs), you'll need that.

**Comment by jakobwes** [comment]
Okay, that's fair ^^. Is there then a way of implementing it, without having another label in the left menu, or not showing this label? If not then I can also just implement it and then when the new frontend launches we can take it out, since there the linking between navigation and taxonomy seems to be automatic.

**Comment by kulla** [comment]
> I can also just implement it and then when the new frontend launches we can take it out, since there the linking between navigation and taxonomy seems to be automatic.

I think that is the best solution.

**Comment by CarolinJaser** [comment]
This is not relevant any longer since it does not occur in the new frontend. Since we are very close to switching to 100% new frontend anyway, I am closing this issue
