### ISSUE TITLE
Redo button is not working

### ISSUE THREAD

**Issue by kulla** [serlo/serlo.org#565]

**Comment by inyono** [comment]
More context: the redo button seems to be disabled all the time (while the undo button is active all the time). Either a wrong integration somehow or the corresponding store selectors are buggy in https://github.com/edtr-io/edtr-io.

**Comment by kulla** [comment]
Do you know whether the redo button worked already? @yolo-bird Can you give insides here?

**Comment by Entkenntnis** [comment]
You can still redo with Ctrl-Y. This seems to work fine. But the button is indeen broken.

**Comment by inyono** [comment]
https://github.com/edtr-io/edtr-io/pull/336 is the requirement for the actual fix.
