### ISSUE TITLE
course pages are  shown/added twice

### ISSUE THREAD

**Issue by metzgaria** [serlo/serlo.org#574]
After saving a new course ([https://de.serlo.org/188999](https://de.serlo.org/188999)) all the coursepages are shown twice. 
(The course is shown in the correct order and then again the whole course in the correct order underneath)
This does not happen every time afaik.
I saved the edit (of the whole course), forgot to check the "without reviewing" box, checked it fastly and saved it again while the first save was still going on.

**Comment by CarolinJaser** [comment]
In Backlog (https://docs.google.com/document/d/1rSkFo2JtsSwHHsbosQcgAN4EzeePXLnqi_eCFpUM3u4/edit#) verschoben
