### ISSUE TITLE
Delete license nr. 2,3,5,8,11,12,15

### ISSUE THREAD

**Issue by yolo-bird** [serlo/serlo.org#577]
Those licenses are not needed any longer, since we do not have and do not intend to have content with that license in the future. 

(I also saw that I have the possibility to delete licenses in the backend. So in case this is sufficient, I could also to it).

**Comment by inyono** [comment]
IMHO:
- Re-check via database if the license is really safe to delete.
- Add migration that removes those

**Comment by kulla** [comment]
Will be done in https://github.com/serlo/api.serlo.org/issues/601...
