### ISSUE TITLE
RFC: Manage subscriptions

### ISSUE THREAD

**Issue by elbotho** [serlo/serlo.org#594]
Currently we subscribe users to content/discussions they interacted with by default and then offer the option to remove subscriptions (and mails for them) **one by one**.
(good luck trying to unsubscribe > 1000 subscriptions 😸)

How big of a problem this is for authors?

**Idea**
Best case would probably be to have user friendly groups (e.g like "Discussions I participated in" and "Discussions related to content I follow" etc…) and let users decide if they want notifs and or mails for that group.

This is also quite complex technically, so maybe we could aim for a compromise: 
Offer the option to filter out by event type, this way we have 16 options but it's a lot easier to implement.

And a global: "No mails please" is a must imo.

```
CreateEntity,
CreateEntityLink,
CreateEntityRevision,
CreateTaxonomyTerm,
CreateTaxonomyLink,
RemoveEntityLink,
RemoveTaxonomyLink,
SetTaxonomyParent,
SetTaxonomyTerm,
SetLicense,
SetUuidState,
CreateComment,
CreateThread,
SetThreadState,
CheckoutRevision,
RejectRevision,
```

**Comment by inyono** [comment]
This is a topic we already have in mind for the new commenting system. Details TBD, though. There are definitely some edge cases that are annoying (you can for example look at what GitHub is doing: even with some "default" setting when to subscribe to something, you still want to be able to opt-out for single discussions that are no longer relevant to you. And on the other hand, you might want to subscribe something you haven't participated in).

So yeah, changes to the notifications system are somewhat on the roadmap and parts of that might be addressed with the new commenting system (which at least covers the notifications that are relevant for learners).

**Comment by CarolinJaser** [comment]
Moved to Google Doc https://docs.google.com/document/d/1rSkFo2JtsSwHHsbosQcgAN4EzeePXLnqi_eCFpUM3u4/edit#
