### ISSUE TITLE
solution invisible

### ISSUE THREAD

**Issue by kathongi** [serlo/serlo.org#638]
The solution of the exercise https://de.serlo.org/209112 with the ID https://de.serlo.org/210136 isn't shown in the old design in the folder https://de.serlo.org/121941

![image](https://user-images.githubusercontent.com/44167220/118668073-d34eeb80-b7f4-11eb-8493-4402dd804ad3.png)

If I click on edit, the whole (very long) solution is visible

**Comment by kathongi** [comment]
ping @kulla

**Comment by kulla** [comment]
The solution is no visible (also in the old design). I guess it was just a caching issue...
