### ISSUE TITLE
Enable GA / Hotjar only after user accepted privacy policy

### ISSUE THREAD

**Issue by inyono** [serlo/serlo.org#66]
Rough approach:
- Add privacy policy to user profile
- Check if current privacy policy has been accepted (see `consent_banner`)
- If yes, we can add GA / Hotjar tracking code at page load already
- If not, we need to wait for the user to accept the privacy policy and load the scripts asynchronously

Other things to note:
- Privacy policy opt-in should ask for different kind of tracking cookies (e.g. "Accept all", "Reject all", "Customize")
- Probably need to refactor current tracking approach (i.e. make it customizable). Server accepts configuration. If set, pass down some global variable to client.

**Comment by yolo-bird** [comment]
not relevant any longer
